use alloy_primitives::{Address, B256, BlockNumber, Bytes, keccak256};
use serde::{Deserialize, Serialize};

/// The proving backend that should generate a proof.
///
/// This is a routing concept internal to the proving pipeline: it selects
/// which worker pool picks up the job.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProofBackend {
    /// SP1 zkVM validity proof.
    Sp1,
    /// AWS Nitro TEE attestation.
    Nitro,
}

impl std::fmt::Display for ProofBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Sp1 => write!(f, "sp1"),
            Self::Nitro => write!(f, "nitro"),
        }
    }
}

/// The proof request sent from a defender
/// to the `prover-service`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofRequest {
    /// The backend that should generate the proof.
    pub backend: ProofBackend,
    /// The `WorldChainProofSystemGame` contract address the proof defends.
    pub game: Address,
    /// The output root claim to prove.
    pub root_claim: B256,
    /// The L2 block number the `root_claim` refers to.
    pub l2_block_number: BlockNumber,
    /// The L1 head hash pinning the witness data.
    pub l1_head: B256,
}

impl ProofRequest {
    /// Compute the deterministic identifier of this request.
    ///
    /// The id is a commitment to every request field, so requesting the
    /// same proof twice yields the same id and the duplicate is deduplicated
    /// by the `prover-service`.
    #[must_use]
    pub fn id(&self) -> ProofRequestId {
        let mut buf = Vec::with_capacity(1 + 20 + 32 + 8 + 32);
        buf.push(self.backend as u8);
        buf.extend_from_slice(self.game.as_slice());
        buf.extend_from_slice(self.root_claim.as_slice());
        buf.extend_from_slice(&self.l2_block_number.to_be_bytes());
        buf.extend_from_slice(self.l1_head.as_slice());
        ProofRequestId(keccak256(buf))
    }
}

/// The unique identifier of a proof request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProofRequestId(pub B256);

impl std::fmt::Display for ProofRequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// The identifier of a single proving lease.
///
/// A fresh lease id is issued every time a job is handed to a worker, so
/// the `prover-service` can tell reports from the current lease holder
/// apart from reports of workers whose lease has already expired.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LeaseId(pub u64);

impl std::fmt::Display for LeaseId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// A proof request leased to a worker by the `prover-service`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LeasedProof {
    /// The leased proof request.
    pub request: ProofRequest,
    /// The lease under which the worker holds this job.
    pub lease: LeaseId,
}

/// The lifecycle state of a proof request inside the `prover-service`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofStatus {
    /// Waiting in the backend queue for a worker.
    Queued,
    /// Leased to a worker that is generating the proof.
    InProgress,
    /// Proof generated and available via `get_proof`.
    Completed,
    /// Permanently failed after exhausting all attempts.
    Failed,
}

impl std::fmt::Display for ProofStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "queued"),
            Self::InProgress => write!(f, "in progress"),
            Self::Completed => write!(f, "completed"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

/// The proof payload generated by a backend.
///
/// The `prover-service` stores and forwards these payloads without
/// interpreting them, verification happens on-chain.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofData {
    /// SP1 zkVM validity proof.
    Sp1 {
        /// Serialized SP1 proof.
        proof: Bytes,
        /// Public values committed by the program.
        public_values: Bytes,
    },
    /// AWS Nitro TEE attestation.
    Nitro {
        /// Attestation document produced by the enclave.
        attestation: Bytes,
        /// Enclave signature over the proven outputs.
        signature: Bytes,
    },
}

impl ProofData {
    /// The backend that produced this proof.
    #[must_use]
    pub const fn backend(&self) -> ProofBackend {
        match self {
            Self::Sp1 { .. } => ProofBackend::Sp1,
            Self::Nitro { .. } => ProofBackend::Nitro,
        }
    }
}

/// The response sent by the `prover-service` to
/// a defender that requests the proof back.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofResponse {
    /// The identifier of the proof request this proof answers.
    pub id: ProofRequestId,
    /// The generated proof.
    pub proof: ProofData,
}
