use alloy_primitives::{Address, B256, BlockNumber, Bytes, keccak256};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The proving backend that should generate a proof.
///
/// This is a routing concept internal to the proving pipeline: it selects
/// which worker pool picks up the job.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProofBackend {
    /// SP1 zkVM validity proof.
    Sp1,
    /// AWS Nitro TEE attestation.
    Nitro,
}

impl std::fmt::Display for ProofBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Sp1 => write!(f, "sp1"),
            Self::Nitro => write!(f, "nitro"),
        }
    }
}

impl ProofBackend {
    /// Stable database representation.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Sp1 => "sp1",
            Self::Nitro => "nitro",
        }
    }
}

impl TryFrom<&str> for ProofBackend {
    type Error = String;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "sp1" => Ok(Self::Sp1),
            "nitro" => Ok(Self::Nitro),
            other => Err(format!("unknown proof backend {other:?}")),
        }
    }
}

/// The proof request sent from a defender
/// to the `prover-service`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofRequest {
    /// The backend that should generate the proof.
    pub backend: ProofBackend,
    /// The `WorldChainProofSystemGame` contract address the proof defends.
    pub game: Address,
    /// The output root claim to prove.
    pub root_claim: B256,
    /// The L2 block number the `root_claim` refers to.
    pub l2_block_number: BlockNumber,
    /// The L1 head hash pinning the witness data.
    pub l1_head: B256,
}

impl ProofRequest {
    /// Compute the deterministic identifier of this request.
    ///
    /// The id is a commitment to every request field, so requesting the
    /// same proof twice yields the same id and the duplicate is deduplicated
    /// by the `prover-service`.
    #[must_use]
    pub fn id(&self) -> ProofRequestId {
        let mut buf = Vec::with_capacity(1 + 20 + 32 + 8 + 32);
        buf.push(self.backend as u8);
        buf.extend_from_slice(self.game.as_slice());
        buf.extend_from_slice(self.root_claim.as_slice());
        buf.extend_from_slice(&self.l2_block_number.to_be_bytes());
        buf.extend_from_slice(self.l1_head.as_slice());
        ProofRequestId(keccak256(buf))
    }
}

/// The unique identifier of a proof request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProofRequestId(pub B256);

impl std::fmt::Display for ProofRequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// The lifecycle state of a proof request inside the `prover-service`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofStatus {
    /// Waiting in the backend queue for a worker.
    Queued,
    /// Leased to a worker that is starting backend work.
    Starting,
    /// External backend work has been requested and is being polled.
    BackendPending,
    /// Proof generated and available via `get_proof`.
    Completed,
    /// Permanently failed after exhausting all attempts.
    Failed,
}

impl std::fmt::Display for ProofStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "queued"),
            Self::Starting => write!(f, "starting"),
            Self::BackendPending => write!(f, "backend pending"),
            Self::Completed => write!(f, "completed"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

impl ProofStatus {
    /// Stable database representation.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Queued => "queued",
            Self::Starting => "starting",
            Self::BackendPending => "backend_pending",
            Self::Completed => "completed",
            Self::Failed => "failed",
        }
    }
}

impl TryFrom<&str> for ProofStatus {
    type Error = String;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "queued" => Ok(Self::Queued),
            "starting" => Ok(Self::Starting),
            "backend_pending" => Ok(Self::BackendPending),
            "completed" => Ok(Self::Completed),
            "failed" => Ok(Self::Failed),
            other => Err(format!("unknown proof status {other:?}")),
        }
    }
}

/// The proof payload generated by a backend.
///
/// The `prover-service` stores and forwards these payloads without
/// interpreting them, verification happens on-chain.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofData {
    /// SP1 zkVM validity proof.
    Sp1 {
        /// Serialized SP1 proof.
        proof: Bytes,
        /// Public values committed by the program.
        public_values: Bytes,
    },
    /// AWS Nitro TEE attestation.
    Nitro {
        /// Attestation document produced by the enclave.
        attestation: Bytes,
        /// Enclave signature over the proven outputs.
        signature: Bytes,
    },
}

impl ProofData {
    /// The backend that produced this proof.
    #[must_use]
    pub const fn backend(&self) -> ProofBackend {
        match self {
            Self::Sp1 { .. } => ProofBackend::Sp1,
            Self::Nitro { .. } => ProofBackend::Nitro,
        }
    }
}

/// The response sent by the `prover-service` to
/// a defender that requests the proof back.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofResponse {
    /// The identifier of the proof request this proof answers.
    pub id: ProofRequestId,
    /// The generated proof.
    pub proof: ProofData,
}

/// Durable status of an external backend proof job.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SessionStatus {
    /// External backend work was requested and is awaiting polling.
    Requested,
    /// External backend work completed successfully.
    Completed,
    /// External backend work reached a terminal failure.
    Failed,
}

impl SessionStatus {
    /// Stable database representation.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Requested => "requested",
            Self::Completed => "completed",
            Self::Failed => "failed",
        }
    }

    /// Whether this status represents a terminal backend session.
    pub const fn is_terminal(&self) -> bool {
        matches!(self, Self::Completed | Self::Failed)
    }
}

impl TryFrom<&str> for SessionStatus {
    type Error = String;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "REQUESTED" => Ok(Self::Requested),
            "COMPLETED" => Ok(Self::Completed),
            "FAILED" => Ok(Self::Failed),
            other => Err(format!("Unknown session status: {other}")),
        }
    }
}

/// External backend request identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BackendProofId(pub B256);

impl std::fmt::Display for BackendProofId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Durable backend proof phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BackendProofPhase {
    /// SP1 compressed range proof phase.
    Range,
    /// SP1 aggregation proof phase.
    Aggregation,
    /// Single external backend request phase.
    Single,
}

impl BackendProofPhase {
    /// Stable database representation.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Range => "range",
            Self::Aggregation => "aggregation",
            Self::Single => "single",
        }
    }
}

impl std::fmt::Display for BackendProofPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for BackendProofPhase {
    type Error = String;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "range" => Ok(Self::Range),
            "aggregation" => Ok(Self::Aggregation),
            "single" => Ok(Self::Single),
            other => Err(format!("unknown backend proof phase {other:?}")),
        }
    }
}

/// Opaque token proving ownership of a locked row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LockId(pub Uuid);

impl LockId {
    /// Generate a fresh lock id.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for LockId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for LockId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Initial proof request locked from `proof_requests`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedProofRequest {
    /// The user-facing proof request.
    pub request: ProofRequest,
    /// Token required for updates to the locked proof job.
    pub lock_id: LockId,
}

/// Durable external backend state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BackendProofState {
    /// SP1 compressed range proof.
    Range {
        /// External backend request id.
        id: BackendProofId,
    },
    /// SP1 aggregation proof.
    Aggregation {
        /// External backend request id.
        id: BackendProofId,
    },
    /// One backend request directly produces the final proof.
    Single {
        /// External backend request id.
        id: BackendProofId,
    },
}

impl BackendProofState {
    /// Durable phase for this backend proof state.
    #[must_use]
    pub const fn phase(self) -> BackendProofPhase {
        match self {
            Self::Range { .. } => BackendProofPhase::Range,
            Self::Aggregation { .. } => BackendProofPhase::Aggregation,
            Self::Single { .. } => BackendProofPhase::Single,
        }
    }

    /// The contained external backend request id.
    #[must_use]
    pub const fn id(self) -> BackendProofId {
        match self {
            Self::Range { id } | Self::Aggregation { id } | Self::Single { id } => id,
        }
    }

    /// Rebuild from phase and backend request id.
    #[must_use]
    pub const fn from_phase(phase: BackendProofPhase, id: BackendProofId) -> Self {
        match phase {
            BackendProofPhase::Range => Self::Range { id },
            BackendProofPhase::Aggregation => Self::Aggregation { id },
            BackendProofPhase::Single => Self::Single { id },
        }
    }
}

/// Backend work returned from a durable backend job.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BackendProofWork {
    /// The original user-facing proof request.
    pub proof_request: ProofRequest,
    /// Opaque backend state to advance.
    pub state: BackendProofState,
}

/// Durable backend job locked from `proof_sessions`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedBackendProofWork {
    /// Database identifier of the backend job row.
    pub backend_job_id: i64,
    /// Backend work to advance.
    pub work: BackendProofWork,
    /// Token required for updates to the locked backend job.
    pub lock_id: LockId,
}

/// Locked location for final proof submission.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofSubmissionLock {
    /// Final proof was produced while starting a user-facing proof job.
    ProofJob {
        /// Token for the locked `proof_requests` row.
        lock_id: LockId,
    },
    /// Final proof was produced while advancing a durable backend job.
    BackendJob {
        /// Database identifier of the backend job row.
        backend_job_id: i64,
        /// Token for the locked `proof_sessions` row.
        lock_id: LockId,
    },
}

/// Result of starting or advancing backend work.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BackendUpdate {
    /// Backend work was requested externally and must be polled later.
    Pending {
        /// Durable backend state.
        state: BackendProofState,
    },
    /// Final proof is complete.
    Complete(ProofData),
    /// Terminal backend failure.
    Failed(String),
    /// No state change; poll again later.
    Noop,
}

/// The session type used to differentiate the proof type
/// returned by SP1 backend.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SessionType {
    /// The range proof.
    Stark,
    /// The final snark groth16 proof.
    Snark,
}

impl SessionType {
    /// Convert enum to static string representation
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Stark => "STARK",
            Self::Snark => "SNARK",
        }
    }
}

impl TryFrom<&str> for SessionType {
    type Error = String;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "STARK" => Ok(Self::Stark),
            "SNARK" => Ok(Self::Snark),
            other => Err(format!("Unknown session type: {other}")),
        }
    }
}

/// A backend session tracked in the prover service for a proof job.
///
/// Workers record the backend-issued identifier (for example an SP1 cluster or
/// network proof id) so a restart or reclaim resumes the in-flight backend job
/// rather than re-running it. The worker itself holds no local state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BackendSession {
    /// Backend-specific session identifier used to resume polling.
    pub backend_session_id: String,
    /// Current backend session lifecycle state.
    pub state: BackendSessionState,
}

/// Lifecycle state of a tracked backend session.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BackendSessionState {
    /// Reservation placeholder before the backend job has been submitted.
    Submitting,
    /// Backend session is actively running.
    Running,
    /// Backend session completed successfully.
    Completed,
    /// Backend session failed.
    Failed,
}

impl BackendSessionState {
    /// Convert enum to static string representation
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Submitting => "SUBMITTING",
            Self::Running => "RUNNING",
            Self::Completed => "COMPLETED",
            Self::Failed => "FAILED",
        }
    }
}

impl TryFrom<&str> for BackendSessionState {
    type Error = String;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "SUBMITTING" => Ok(Self::Submitting),
            "RUNNING" => Ok(Self::Running),
            "COMPLETED" => Ok(Self::Completed),
            "FAILED" => Ok(Self::Failed),
            other => Err(format!("Unknown session status: {other}")),
        }
    }
}
