//! The `measurements.lock` document: what the proof system commits to at this commit.

use alloy_primitives::keccak256;
use eyre::eyre::{bail, eyre};
use serde::{Deserialize, Serialize};

/// Current schema version of `measurements.lock`.
pub const SCHEMA_VERSION: u32 = 1;

/// Path of the lockfile relative to the repo root.
pub const LOCK_PATH: &str = "measurements.lock";

/// SP1 guest measurements. The vkeys are a deterministic function of the ELFs, so a build
/// only has to check the ELF hashes to know the vkeys cannot have moved.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Sp1 {
    /// Aggregation program verification key.
    pub aggregation_vkey: String,
    /// Range program verification-key commitment.
    pub range_vkey_commitment: String,
    /// SHA-256 of the compiled guest ELFs.
    pub elf: Sp1Elf,
}

/// SHA-256 of each compiled SP1 guest ELF.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Sp1Elf {
    /// `world-chain-aggregation` ELF digest.
    pub aggregation_sha256: String,
    /// `world-chain-range-ethereum` ELF digest.
    pub range_sha256: String,
}

/// Nitro enclave measurements, plus the cheap input digests a build can assert against
/// without producing an EIF (PCRs only exist after `nitro-cli build-enclave`).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Nitro {
    /// EIF measurement (kernel + cmdline + all ramdisks).
    pub pcr0: String,
    /// Kernel + bootstrap ramdisk measurement.
    pub pcr1: String,
    /// Application ramdisk measurement.
    pub pcr2: String,
    /// `keccak256(pcr0)` — how the on-chain registry keys enclave images.
    pub tee_image_id: String,
    /// SHA-256 of the enclave binary, asserted during the image build.
    pub binary_sha256: String,
    /// SHA-256 of the enclave Dockerfile; catches pin changes that leave the binary alone.
    pub dockerfile_sha256: String,
    /// nitro-cli tag that supplies the kernel and bootstrap ramdisk, and so fixes PCR1.
    pub cli_version: String,
}

/// The whole lockfile.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lock {
    /// Schema version, so the format can change without guesswork.
    pub version: u32,
    /// SP1 backend measurements.
    pub sp1: Sp1,
    /// Nitro backend measurements.
    pub nitro: Nitro,
}

const HEADER: &str = "\
# This file is @generated by `cargo xtask measure`. Do not edit.
#
# What the proof system commits to, rebuilt from source. CI runs
# `cargo xtask measure --check`, which rebuilds and fails if anything here is stale;
# compiling the guests or the enclave image also asserts the input digests below.
#
# Regenerate with `cargo xtask measure` (Linux x86_64 + Docker) and commit the diff.
#
# Every value here decides which proofs the on-chain verifiers will accept. A change
# here is a change to the system's trust anchors — review it as one.
";

impl Lock {
    /// Parses and validates a lockfile.
    pub fn parse(text: &str) -> eyre::Result<Self> {
        let lock: Self = toml::from_str(text).map_err(|e| eyre!("{LOCK_PATH}: {e}"))?;
        lock.validate()?;
        Ok(lock)
    }

    /// Renders the lockfile, header comment included, exactly as `measure` writes it.
    pub fn render(&self) -> eyre::Result<String> {
        let body =
            toml::to_string_pretty(self).map_err(|e| eyre!("serialising {LOCK_PATH}: {e}"))?;
        Ok(format!("{HEADER}\n{body}"))
    }

    /// Rejects malformed digests and a `tee_image_id` that does not derive from `pcr0`.
    ///
    /// Shape is worth checking on the way in as well as on the way out: a truncated or
    /// uppercased digest that round-trips through the file would silently change which
    /// enclave image the registry trusts.
    pub fn validate(&self) -> eyre::Result<()> {
        if self.version != SCHEMA_VERSION {
            bail!(
                "{LOCK_PATH}: schema version {} is not supported (expected {SCHEMA_VERSION})",
                self.version
            );
        }

        for (field, value, nibbles, prefixed) in [
            ("sp1.aggregation_vkey", &self.sp1.aggregation_vkey, 64, true),
            (
                "sp1.range_vkey_commitment",
                &self.sp1.range_vkey_commitment,
                64,
                true,
            ),
            (
                "sp1.elf.aggregation_sha256",
                &self.sp1.elf.aggregation_sha256,
                64,
                false,
            ),
            (
                "sp1.elf.range_sha256",
                &self.sp1.elf.range_sha256,
                64,
                false,
            ),
            ("nitro.pcr0", &self.nitro.pcr0, 96, false),
            ("nitro.pcr1", &self.nitro.pcr1, 96, false),
            ("nitro.pcr2", &self.nitro.pcr2, 96, false),
            ("nitro.tee_image_id", &self.nitro.tee_image_id, 64, true),
            ("nitro.binary_sha256", &self.nitro.binary_sha256, 64, false),
            (
                "nitro.dockerfile_sha256",
                &self.nitro.dockerfile_sha256,
                64,
                false,
            ),
        ] {
            check_hex(field, value, nibbles, prefixed)?;
        }

        let derived = derive_tee_image_id(&self.nitro.pcr0)?;
        if derived != self.nitro.tee_image_id {
            bail!(
                "{LOCK_PATH}: nitro.tee_image_id {} != keccak256(pcr0) = {derived}",
                self.nitro.tee_image_id
            );
        }

        if self.nitro.cli_version.is_empty() {
            bail!("{LOCK_PATH}: nitro.cli_version is empty");
        }

        Ok(())
    }

    /// Human-readable field-by-field difference, for the `--check` failure message.
    pub fn diff(&self, other: &Self) -> Vec<String> {
        let mut out = Vec::new();
        let mut cmp = |field: &str, a: &str, b: &str| {
            if a != b {
                out.push(format!("  {field}\n    lock:  {a}\n    built: {b}"));
            }
        };
        cmp(
            "sp1.aggregation_vkey",
            &self.sp1.aggregation_vkey,
            &other.sp1.aggregation_vkey,
        );
        cmp(
            "sp1.range_vkey_commitment",
            &self.sp1.range_vkey_commitment,
            &other.sp1.range_vkey_commitment,
        );
        cmp(
            "sp1.elf.aggregation_sha256",
            &self.sp1.elf.aggregation_sha256,
            &other.sp1.elf.aggregation_sha256,
        );
        cmp(
            "sp1.elf.range_sha256",
            &self.sp1.elf.range_sha256,
            &other.sp1.elf.range_sha256,
        );
        cmp("nitro.pcr0", &self.nitro.pcr0, &other.nitro.pcr0);
        cmp("nitro.pcr1", &self.nitro.pcr1, &other.nitro.pcr1);
        cmp("nitro.pcr2", &self.nitro.pcr2, &other.nitro.pcr2);
        cmp(
            "nitro.tee_image_id",
            &self.nitro.tee_image_id,
            &other.nitro.tee_image_id,
        );
        cmp(
            "nitro.binary_sha256",
            &self.nitro.binary_sha256,
            &other.nitro.binary_sha256,
        );
        cmp(
            "nitro.dockerfile_sha256",
            &self.nitro.dockerfile_sha256,
            &other.nitro.dockerfile_sha256,
        );
        cmp(
            "nitro.cli_version",
            &self.nitro.cli_version,
            &other.nitro.cli_version,
        );
        out
    }
}

/// `0x`-prefixed `keccak256(pcr0)`, the identifier the on-chain registry uses.
pub fn derive_tee_image_id(pcr0: &str) -> eyre::Result<String> {
    let bytes = hex::decode(pcr0).map_err(|e| eyre!("pcr0 is not hex: {e}"))?;
    Ok(format!("0x{:x}", keccak256(bytes)))
}

fn check_hex(field: &str, value: &str, nibbles: usize, prefixed: bool) -> eyre::Result<()> {
    let hex = match (prefixed, value.strip_prefix("0x")) {
        (true, Some(rest)) => rest,
        (true, None) => bail!("{LOCK_PATH}: {field} must be 0x-prefixed"),
        (false, Some(_)) => bail!("{LOCK_PATH}: {field} must not be 0x-prefixed"),
        (false, None) => value,
    };
    if hex.len() != nibbles
        || !hex
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    {
        bail!("{LOCK_PATH}: {field} must be {nibbles} lowercase hex characters");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// PCR0 and its real keccak256, taken from release 1.0.0-rc.3.
    const PCR0: &str = "dc0dc88dc8e2aba973679fc9a8381f422e9f49e0e435dc99bdc32aebeeaf12fa2265699bf0ce4bf84fbf3cb35e72549b";
    const TEE_IMAGE_ID: &str = "0xe6bad10605f4bb2df98e45cd5c400f3374a6d629696231e698ee958c81300621";

    fn lock() -> Lock {
        Lock {
            version: SCHEMA_VERSION,
            sp1: Sp1 {
                aggregation_vkey: format!("0x{}", "1".repeat(64)),
                range_vkey_commitment: format!("0x{}", "2".repeat(64)),
                elf: Sp1Elf {
                    aggregation_sha256: "3".repeat(64),
                    range_sha256: "4".repeat(64),
                },
            },
            nitro: Nitro {
                pcr0: PCR0.to_string(),
                pcr1: "5".repeat(96),
                pcr2: "6".repeat(96),
                tee_image_id: TEE_IMAGE_ID.to_string(),
                binary_sha256: "7".repeat(64),
                dockerfile_sha256: "8".repeat(64),
                cli_version: "v1.4.2".to_string(),
            },
        }
    }

    /// The `tee_image_id` recorded on-chain must be exactly `keccak256(pcr0)`; this pins the
    /// derivation against a value produced by a real release so a hashing change is caught.
    #[test]
    fn tee_image_id_derives_from_pcr0() {
        assert_eq!(derive_tee_image_id(PCR0).unwrap(), TEE_IMAGE_ID);
    }

    #[test]
    fn round_trips_through_toml() {
        let original = lock();
        let rendered = original.render().unwrap();
        assert_eq!(Lock::parse(&rendered).unwrap(), original);
    }

    /// The rendered file must keep the "@generated" banner, or someone will hand-edit it.
    #[test]
    fn render_keeps_generated_header() {
        assert!(lock().render().unwrap().contains("@generated"));
    }

    #[test]
    fn rejects_tee_image_id_that_does_not_match_pcr0() {
        let mut lock = lock();
        lock.nitro.tee_image_id = format!("0x{}", "9".repeat(64));
        let err = lock.validate().unwrap_err().to_string();
        assert!(err.contains("keccak256(pcr0)"), "got: {err}");
    }

    #[test]
    fn rejects_wrong_length_digest() {
        let mut lock = lock();
        lock.nitro.pcr0 = "ab".to_string();
        assert!(lock.validate().is_err());
    }

    #[test]
    fn rejects_uppercase_hex() {
        let mut lock = lock();
        lock.sp1.elf.range_sha256 = "A".repeat(64);
        assert!(lock.validate().is_err());
    }

    #[test]
    fn rejects_missing_0x_prefix() {
        let mut lock = lock();
        lock.sp1.aggregation_vkey = "1".repeat(64);
        assert!(lock.validate().is_err());
    }

    #[test]
    fn rejects_unexpected_0x_prefix() {
        let mut lock = lock();
        lock.sp1.elf.range_sha256 = format!("0x{}", "4".repeat(64));
        assert!(lock.validate().is_err());
    }

    #[test]
    fn rejects_unknown_schema_version() {
        let mut lock = lock();
        lock.version = SCHEMA_VERSION + 1;
        assert!(lock.validate().is_err());
    }

    #[test]
    fn diff_names_every_changed_field_and_nothing_else() {
        let a = lock();
        let mut b = a.clone();
        b.nitro.pcr2 = "0".repeat(96);
        b.sp1.elf.range_sha256 = "1".repeat(64);

        let diff = a.diff(&b);
        assert_eq!(diff.len(), 2, "{diff:#?}");
        assert!(diff.iter().any(|d| d.contains("nitro.pcr2")));
        assert!(diff.iter().any(|d| d.contains("sp1.elf.range_sha256")));
        assert!(a.diff(&a).is_empty());
    }
}
