[package]
name = "flashblocks-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true


[dependencies]
# reth
reth-chain-state.workspace = true
reth-node-api.workspace = true
reth-provider.workspace = true
