//! Wire protocol shared by the Nitro host and the in-enclave guest binary.
//!
//! Framing is intentionally trivial: each message is `u64` big-endian length followed by a
//! CBOR-encoded [`EnclaveRequest`] or [`EnclaveResponse`]. We deliberately avoid using rkyv
//! for the outer envelope so that the protocol stays decoupled from the inner witness format
//! and can be evolved (versioned) without re-generating archived layouts. The inner witness
//! payload is rkyv-encoded [`WorldRangeWitnessData`] because that is what the SP1 range
//! program already consumes.

use alloy_primitives::B256;
use alloy_sol_types::SolValue;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::TryReserveError;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use world_chain_proof_core::boot::TransitionPublicValues;

/// Current protocol version. Bumped whenever the wire format changes incompatibly.
pub const PROTOCOL_VERSION: u32 = 1;

/// Default vsock port the enclave binary listens on.
pub const DEFAULT_VSOCK_PORT: u32 = 5005;

/// Maximum frame size accepted on the wire (2 GiB).
///
/// The cap prevents a malformed peer-controlled length prefix from forcing an unbounded
/// allocation inside the enclave. Nitro deployments must provision enough memory for both the
/// encoded frame and the decoded witness to coexist temporarily.
pub const MAX_FRAME_BYTES: usize = 2 * 1024 * 1024 * 1024;

/// Maximum bytes passed to one vsock `write` operation.
///
/// Keeping writes below the Linux linear-SKB threshold avoids corruption observed when large
/// virtio-vsock writes are represented by nonlinear, multi-descriptor socket buffers.
const MAX_WRITE_BYTES: usize = 28 * 1024;

/// Requests the host can send to the enclave.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnclaveRequest {
    /// Prove a single range transition.
    Range {
        /// Protocol version the host expects.
        version: u32,
        /// rkyv-serialized `WorldRangeWitnessData`.
        ///
        /// `serde_bytes` is required here so CBOR represents the witness as one byte string
        /// instead of an array of individually encoded integers.
        #[serde(with = "serde_bytes")]
        witness_rkyv: Vec<u8>,
        /// Optional host-computed public values the enclave must match before signing.
        expected_transition_public_values: Option<TransitionPublicValues>,
        /// 32-byte random nonce generated by the host. The enclave passes it to the NSM
        /// so it is embedded in the signed attestation payload, preventing replay attacks.
        nonce: [u8; 32],
    },
    /// Request an NSM attestation document that embeds the enclave's ephemeral public key.
    ///
    /// Used during one-time registration: the host can verify the attestation doc to learn
    /// the enclave's current secp256k1 public key and trust it for subsequent proof signatures.
    PublicKey {
        /// 32-byte random nonce for replay protection (see `Range::nonce`).
        nonce: [u8; 32],
    },
    /// Request a bare NSM attestation document without running any proof.
    ///
    /// Used for CertManager pre-warm: operators need a real attestation document from
    /// a running enclave so the AWS Nitro CA cert chain can be extracted and registered
    /// on L1 before any `registerKey` call can succeed.
    GetAttestation,
}

/// Responses the enclave can return to the host.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnclaveResponse {
    /// Successful range proof.
    Range {
        /// Transition public values committed by the enclave.
        transition_public_values: TransitionPublicValues,
        /// `COSE_Sign1` attestation document bytes from the NSM device.
        attestation_doc: Vec<u8>,
        /// 65-byte recoverable secp256k1 signature over the ABI-encoded transition public values.
        ///
        /// The signing key is the enclave's ephemeral keypair, whose public key is
        /// certified by the NSM attestation document via [`EnclaveRequest::PublicKey`].
        signature: Vec<u8>,
    },
    /// NSM attestation document that embeds the enclave's ephemeral secp256k1 public key.
    ///
    /// Returned in response to [`EnclaveRequest::PublicKey`]. The host can verify the
    /// document and extract `public_key` to trust subsequent proof signatures.
    Attestation {
        /// `COSE_Sign1` attestation document bytes. The `public_key` field inside the
        /// document holds the compressed SEC1 encoding of the enclave's secp256k1 key.
        attestation_doc: Vec<u8>,
        /// Compressed SEC1 encoding of the enclave's ephemeral secp256k1 public key
        /// (33 bytes). Included at the top level for convenient extraction without
        /// full document parsing.
        public_key: Vec<u8>,
    },
    /// Bare attestation document returned in response to [`EnclaveRequest::GetAttestation`].
    ///
    /// Contains only the raw `COSE_Sign1` bytes — no proof payload, no public key extraction.
    BareAttestation {
        /// `COSE_Sign1` attestation document bytes from the NSM device.
        attestation_doc: Vec<u8>,
    },
    /// Enclave-side error. The host treats this as a permanent failure for the request.
    Error {
        /// Human-readable error message produced inside the enclave.
        message: String,
    },
}

/// Writes a length-prefixed CBOR frame.
pub async fn write_frame<W, T>(writer: &mut W, value: &T) -> Result<(), FrameError>
where
    W: AsyncWriteExt + Unpin,
    T: Serialize,
{
    let mut buf = Vec::with_capacity(1024);
    ciborium::into_writer(value, &mut buf).map_err(|err| FrameError::Encode(err.to_string()))?;
    if buf.len() > MAX_FRAME_BYTES {
        return Err(FrameError::FrameTooLarge {
            len: buf.len() as u64,
            limit: MAX_FRAME_BYTES,
        });
    }
    let len: u64 = buf
        .len()
        .try_into()
        .map_err(|_| FrameError::LengthOverflow(buf.len()))?;
    writer.write_all(&len.to_be_bytes()).await?;
    for chunk in buf.chunks(MAX_WRITE_BYTES) {
        writer.write_all(chunk).await?;
    }
    writer.flush().await?;
    Ok(())
}

/// Reads a length-prefixed CBOR frame.
pub async fn read_frame<R, T>(reader: &mut R) -> Result<T, FrameError>
where
    R: AsyncReadExt + Unpin,
    T: for<'de> Deserialize<'de>,
{
    let mut len_bytes = [0u8; 8];
    reader.read_exact(&mut len_bytes).await?;
    let wire_len = u64::from_be_bytes(len_bytes);
    if wire_len > MAX_FRAME_BYTES as u64 {
        return Err(FrameError::FrameTooLarge {
            len: wire_len,
            limit: MAX_FRAME_BYTES,
        });
    }
    let len = usize::try_from(wire_len).map_err(|_| FrameError::UnsupportedLength(wire_len))?;
    let mut buf = Vec::new();
    buf.try_reserve_exact(len)
        .map_err(|source| FrameError::Allocation { len, source })?;
    buf.resize(len, 0);
    reader.read_exact(&mut buf).await?;
    let value =
        ciborium::from_reader(buf.as_slice()).map_err(|err| FrameError::Decode(err.to_string()))?;
    Ok(value)
}

/// Errors raised by the wire-framing helpers.
#[derive(Debug, thiserror::Error)]
pub enum FrameError {
    /// IO error reading or writing the underlying transport.
    #[error("vsock io error: {0}")]
    Io(#[from] std::io::Error),
    /// CBOR encoding failed.
    #[error("frame encode failed: {0}")]
    Encode(String),
    /// CBOR decoding failed.
    #[error("frame decode failed: {0}")]
    Decode(String),
    /// Frame exceeds the maximum allowed size.
    #[error("frame too large: {len} bytes exceeds limit of {limit} bytes")]
    FrameTooLarge {
        /// Encoded or peer-declared frame length.
        len: u64,
        /// Maximum accepted frame length.
        limit: usize,
    },
    /// A local encoded buffer cannot be represented by the wire length type.
    #[error("frame length does not fit in u64: {0} bytes")]
    LengthOverflow(usize),
    /// A peer-declared length cannot be represented on the current platform.
    #[error("frame length is unsupported on this platform: {0} bytes")]
    UnsupportedLength(u64),
    /// Memory for an accepted frame could not be reserved.
    #[error("failed to allocate {len} bytes for frame: {source}")]
    Allocation {
        /// Requested allocation length.
        len: usize,
        /// Allocation failure returned by `Vec`.
        #[source]
        source: TryReserveError,
    },
}

/// Computes the canonical commitment used for attestation and signing.
///
/// `keccak256(abi.encode(TransitionPublicValues))`
#[must_use]
pub fn transition_commitment(transition_public_values: &TransitionPublicValues) -> [u8; 32] {
    *alloy_primitives::keccak256(transition_public_values.abi_encode())
}

/// Hashes an arbitrary byte slice and returns it as a 32-byte `B256`.
#[must_use]
pub fn sha256_b256(bytes: &[u8]) -> B256 {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    B256::from_slice(hasher.finalize().as_ref())
}

#[cfg(test)]
mod tests {
    use std::{
        pin::Pin,
        task::{Context, Poll},
    };

    use super::*;
    use alloy_primitives::B256;
    use tokio::io::AsyncWrite;

    #[derive(Default)]
    struct RecordingWriter {
        bytes: Vec<u8>,
        max_write: usize,
    }

    impl AsyncWrite for RecordingWriter {
        fn poll_write(
            mut self: Pin<&mut Self>,
            _cx: &mut Context<'_>,
            buf: &[u8],
        ) -> Poll<std::io::Result<usize>> {
            self.max_write = self.max_write.max(buf.len());
            self.bytes.extend_from_slice(buf);
            Poll::Ready(Ok(buf.len()))
        }

        fn poll_flush(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<std::io::Result<()>> {
            Poll::Ready(Ok(()))
        }

        fn poll_shutdown(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<std::io::Result<()>> {
            Poll::Ready(Ok(()))
        }
    }

    fn transition_public_values() -> TransitionPublicValues {
        TransitionPublicValues {
            l1Head: B256::from([1; 32]),
            l2PreRoot: B256::from([2; 32]),
            l2PreBlockNumber: 41,
            l2PostRoot: B256::from([3; 32]),
            l2PostBlockNumber: 42,
            rollupConfigHash: B256::from([4; 32]),
        }
    }

    #[test]
    fn transition_commitment_is_deterministic() {
        let a = transition_commitment(&transition_public_values());
        let b = transition_commitment(&transition_public_values());
        assert_eq!(a, b);
    }

    #[test]
    fn transition_commitment_depends_on_post_root() {
        let mut transition_public_values = transition_public_values();
        let original = transition_commitment(&transition_public_values);
        transition_public_values.l2PostRoot = B256::from([9; 32]);
        let mutated = transition_commitment(&transition_public_values);
        assert_ne!(original, mutated);
    }

    #[test]
    fn transition_commitment_depends_on_l1_head_and_block_numbers() {
        let original = transition_commitment(&transition_public_values());

        let mut changed_l1_head = transition_public_values();
        changed_l1_head.l1Head = B256::from([9; 32]);
        assert_ne!(original, transition_commitment(&changed_l1_head));

        let mut changed_pre_block = transition_public_values();
        changed_pre_block.l2PreBlockNumber += 1;
        assert_ne!(original, transition_commitment(&changed_pre_block));

        let mut changed_post_block = transition_public_values();
        changed_post_block.l2PostBlockNumber += 1;
        assert_ne!(original, transition_commitment(&changed_post_block));
    }

    #[test]
    fn transition_commitment_hashes_abi_encoded_public_values() {
        let values = transition_public_values();
        assert_eq!(
            transition_commitment(&values),
            *alloy_primitives::keccak256(values.abi_encode())
        );
    }

    #[test]
    fn range_witness_is_encoded_as_a_cbor_byte_string() {
        // Values above CBOR's inline-integer range would take two bytes each if this field were
        // accidentally encoded as an array of integers instead of one byte string.
        let witness_rkyv = vec![0xFF; 4096];
        let request = EnclaveRequest::Range {
            version: PROTOCOL_VERSION,
            witness_rkyv: witness_rkyv.clone(),
            expected_transition_public_values: None,
            nonce: [0; 32],
        };

        let mut encoded = Vec::new();
        ciborium::into_writer(&request, &mut encoded).unwrap();
        let value: ciborium::Value = ciborium::from_reader(encoded.as_slice()).unwrap();
        let ciborium::Value::Map(fields) = value else {
            panic!("range request must encode as a CBOR map");
        };
        let encoded_witness = fields
            .iter()
            .find_map(|(key, value)| match key {
                ciborium::Value::Text(key) if key == "witness_rkyv" => Some(value),
                _ => None,
            })
            .expect("range request must contain witness_rkyv");

        assert_eq!(encoded_witness, &ciborium::Value::Bytes(witness_rkyv));
    }

    #[tokio::test]
    async fn frame_round_trip_uses_u64_length_and_throttled_writes() {
        let witness_rkyv = vec![0xAB; MAX_WRITE_BYTES * 3];
        let request = EnclaveRequest::Range {
            version: PROTOCOL_VERSION,
            witness_rkyv: witness_rkyv.clone(),
            expected_transition_public_values: None,
            nonce: [7; 32],
        };
        let mut writer = RecordingWriter::default();

        write_frame(&mut writer, &request).await.unwrap();

        assert!(writer.max_write <= MAX_WRITE_BYTES);
        let declared_len = u64::from_be_bytes(writer.bytes[..8].try_into().unwrap());
        assert_eq!(declared_len, (writer.bytes.len() - 8) as u64);

        let mut reader = writer.bytes.as_slice();
        let decoded: EnclaveRequest = read_frame(&mut reader).await.unwrap();
        match decoded {
            EnclaveRequest::Range {
                version,
                witness_rkyv: decoded_witness,
                expected_transition_public_values,
                nonce,
            } => {
                assert_eq!(version, PROTOCOL_VERSION);
                assert_eq!(decoded_witness, witness_rkyv);
                assert_eq!(expected_transition_public_values, None);
                assert_eq!(nonce, [7; 32]);
            }
            other => panic!("expected range request, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn oversized_frame_is_rejected_before_reading_a_body() {
        let oversized_len = MAX_FRAME_BYTES as u64 + 1;
        let prefix = oversized_len.to_be_bytes();
        let mut reader = prefix.as_slice();

        let err = read_frame::<_, EnclaveRequest>(&mut reader)
            .await
            .expect_err("oversized length must be rejected");

        assert!(matches!(
            err,
            FrameError::FrameTooLarge {
                len,
                limit: MAX_FRAME_BYTES
            } if len == oversized_len
        ));
    }
}
