use alloy_consensus::BlockHeader;
use alloy_op_evm::OpEvmFactory;
use alloy_primitives::{Address, B256, Bytes, U256};
use alloy_rpc_types::BlockNumberOrTag;
use jsonrpsee::{
    core::{RpcResult, async_trait},
    proc_macros::rpc,
};
use reth_evm::{ConfigureEvm, Evm as RethEvm, EvmFactory, op_revm::OpTransaction};
use reth_optimism_evm::OpEvmConfig;
use reth_provider::{BlockReaderIdExt, HeaderProvider, StateProviderFactory};
use reth_revm::{State, database::StateProviderDatabase};
use revm::{
    Inspector,
    context::{
        TxEnv,
        result::{ExecutionResult, Output},
    },
    interpreter::{CallInputs, CallOutcome},
};
use revm_database::BundleState;
use revm_primitives::TxKind;
use serde::{Deserialize, Serialize};
use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
};

// ═══════════════════════════════════════════════════════════════════════════════
// Request types
// ═══════════════════════════════════════════════════════════════════════════════

/// Request for `worldchain_simulateUnsignedUserOp`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimulateUnsignedUserOpRequest {
    /// The smart account address to call.
    pub sender: Address,
    /// The encoded execution payload (e.g. `executeUserOp` calldata).
    pub call_data: Bytes,
    /// The ERC-4337 EntryPoint address used as `msg.sender` in the simulation.
    pub entry_point: Address,
    /// Block to simulate against. Defaults to `latest`.
    #[serde(default = "default_block")]
    pub block: BlockNumberOrTag,
    /// Optional gas limit for the simulated call. Defaults to 30 000 000.
    #[serde(default)]
    pub call_gas_limit: Option<U256>,
}

fn default_block() -> BlockNumberOrTag {
    BlockNumberOrTag::Latest
}

// ═══════════════════════════════════════════════════════════════════════════════
// Response types
// ═══════════════════════════════════════════════════════════════════════════════

/// The standard a token/asset conforms to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AssetType {
    Native,
    Erc20,
    Erc721,
    Erc1155,
}

/// Token/asset metadata resolved from on-chain state.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetInfo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<Address>,
    pub symbol: String,
    pub name: String,
    pub decimals: u8,
    #[serde(rename = "type")]
    pub asset_type: AssetType,
}

/// A discrete asset transfer detected during simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetChange {
    #[serde(rename = "type")]
    pub change_type: AssetType,
    pub from: Address,
    pub to: Address,
    pub raw_amount: String,
    pub token_id: Option<String>,
    pub asset: AssetInfo,
}

/// An ERC-20/721/1155 token approval detected during simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApprovalChange {
    pub owner: Address,
    pub spender: Address,
    pub raw_amount: String,
    pub is_approved_for_all: bool,
    pub asset: AssetInfo,
}

/// A call made during execution, forming a full stack trace.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TraceEntry {
    pub depth: usize,
    pub from: Address,
    pub to: Address,
    pub method: Option<String>,
    pub selector: String,
    pub value: String,
}

/// Severity level for simulation warnings.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum WarningSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// A warning generated by the node during simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimulationWarning {
    pub severity: WarningSeverity,
    pub message: String,
}

/// Outcome of the simulation execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SimulationStatus {
    Success,
    Revert,
}

/// Full response for `worldchain_simulateUnsignedUserOp`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimulateUnsignedUserOpResult {
    pub status: SimulationStatus,
    pub revert_reason: Option<String>,
    pub block_number: u64,
    pub gas_used: String,
    pub asset_changes: Vec<AssetChange>,
    pub approval_changes: Vec<ApprovalChange>,
    pub trace: Vec<TraceEntry>,
    pub warnings: Vec<SimulationWarning>,
}

// ═══════════════════════════════════════════════════════════════════════════════
// Simulation inspector — captures call trace and native ETH transfers
// ═══════════════════════════════════════════════════════════════════════════════

/// Shared state captured by the simulation inspector.
#[derive(Debug, Default)]
struct InspectorState {
    /// Full call stack trace — every CALL/STATICCALL/DELEGATECALL at every depth.
    traces: Vec<RawTrace>,
    /// Native ETH transfers (calls with value > 0 at any depth).
    native_transfers: Vec<NativeTransfer>,
    /// Current call depth.
    call_depth: usize,
}

#[derive(Debug)]
struct RawTrace {
    depth: usize,
    from: Address,
    to: Address,
    selector: [u8; 4],
    value: U256,
}

#[derive(Debug)]
struct NativeTransfer {
    from: Address,
    to: Address,
    value: U256,
}

/// Captures top-level calls made by the smart account and native ETH transfers.
///
/// Uses `Arc<Mutex>` so the caller can read captured data after the EVM consumes
/// the inspector.
#[derive(Debug, Clone, Default)]
pub struct SimulationInspector {
    state: Arc<Mutex<InspectorState>>,
}

/// Handle returned to the caller for reading captured data after execution.
#[derive(Debug, Clone)]
pub struct InspectorHandle {
    state: Arc<Mutex<InspectorState>>,
}

impl InspectorHandle {
    pub fn take_trace_entries(&self) -> Vec<TraceEntry> {
        let state = self.state.lock().unwrap();
        state
            .traces
            .iter()
            .map(|t| {
                let sel = t.selector;
                TraceEntry {
                    depth: t.depth,
                    from: t.from,
                    to: t.to,
                    method: selector_to_name(sel).map(str::to_string),
                    selector: format!("0x{}", hex::encode(sel)),
                    value: format!("{:#x}", t.value),
                }
            })
            .collect()
    }

    pub fn take_native_asset_changes(&self) -> Vec<AssetChange> {
        let state = self.state.lock().unwrap();
        state
            .native_transfers
            .iter()
            .map(|t| AssetChange {
                change_type: AssetType::Native,
                from: t.from,
                to: t.to,
                raw_amount: t.value.to_string(),
                token_id: None,
                asset: AssetInfo {
                    address: None,
                    symbol: "ETH".to_string(),
                    name: "Ether".to_string(),
                    decimals: 18,
                    asset_type: AssetType::Native,
                },
            })
            .collect()
    }
}

pub fn new_simulation_inspector() -> (SimulationInspector, InspectorHandle) {
    let state = Arc::new(Mutex::new(InspectorState::default()));
    (
        SimulationInspector {
            state: state.clone(),
        },
        InspectorHandle { state },
    )
}

impl<CTX> Inspector<CTX> for SimulationInspector {
    fn call(&mut self, _context: &mut CTX, inputs: &mut CallInputs) -> Option<CallOutcome> {
        let mut state = self.state.lock().unwrap();

        // Record every call at every depth for a full stack trace
        let selector = match &inputs.input {
            revm::interpreter::CallInput::Bytes(b) if b.len() >= 4 => {
                let mut sel = [0u8; 4];
                sel.copy_from_slice(&b[..4]);
                sel
            }
            _ => [0u8; 4],
        };
        let value = inputs.value.transfer().unwrap_or(U256::ZERO);
        let depth = state.call_depth;
        state.traces.push(RawTrace {
            depth,
            from: inputs.caller,
            to: inputs.target_address,
            selector,
            value,
        });

        // Track native ETH transfers at any depth
        if let Some(value) = inputs.value.transfer()
            && value > U256::ZERO
        {
            state.native_transfers.push(NativeTransfer {
                from: inputs.caller,
                to: inputs.target_address,
                value,
            });
        }

        state.call_depth += 1;
        None
    }

    fn call_end(&mut self, _context: &mut CTX, _inputs: &CallInputs, _outcome: &mut CallOutcome) {
        let mut state = self.state.lock().unwrap();
        state.call_depth = state.call_depth.saturating_sub(1);
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// RPC trait
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg_attr(not(test), rpc(server, namespace = "worldchain"))]
#[cfg_attr(test, rpc(server, client, namespace = "worldchain"))]
#[async_trait]
pub trait WorldChainSimulateApi {
    /// Simulates an unsigned ERC-4337 v0.7 PackedUserOperation against the
    /// specified block state. Returns asset transfers, approval changes,
    /// decoded trace, and warnings.
    #[method(name = "simulateUnsignedUserOp")]
    async fn simulate_unsigned_user_op(
        &self,
        request: SimulateUnsignedUserOpRequest,
    ) -> RpcResult<SimulateUnsignedUserOpResult>;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Implementation
// ═══════════════════════════════════════════════════════════════════════════════

/// Cross-request cache for resolved token metadata.
type MetadataCache = Arc<Mutex<HashMap<Address, AssetInfo>>>;

/// Implementation of the `worldchain_simulateUnsignedUserOp` RPC endpoint.
#[derive(Debug, Clone)]
pub struct WorldChainSimulate<Client> {
    client: Client,
    evm_config: OpEvmConfig,
    metadata_cache: MetadataCache,
}

impl<Client> WorldChainSimulate<Client> {
    pub fn new(client: Client, evm_config: OpEvmConfig) -> Self {
        Self {
            client,
            evm_config,
            metadata_cache: Arc::new(Mutex::new(HashMap::new())),
        }
    }
}

#[async_trait]
impl<Client> WorldChainSimulateApiServer for WorldChainSimulate<Client>
where
    Client: BlockReaderIdExt
        + StateProviderFactory
        + HeaderProvider<Header = alloy_consensus::Header>
        + 'static,
{
    async fn simulate_unsigned_user_op(
        &self,
        request: SimulateUnsignedUserOpRequest,
    ) -> RpcResult<SimulateUnsignedUserOpResult> {
        let block_id = request.block.into();

        // 1. Resolve the sealed header for the target block
        let header = self
            .client
            .sealed_header_by_id(block_id)
            .map_err(internal_err)?
            .ok_or_else(|| {
                jsonrpsee::types::ErrorObjectOwned::owned(
                    jsonrpsee::types::error::INVALID_PARAMS_CODE,
                    "Block not found",
                    None::<String>,
                )
            })?;
        let block_number = header.number();

        // 2. Build the EVM environment from the header
        let evm_env = self
            .evm_config
            .evm_env(header.header())
            .map_err(internal_err)?;

        // 3. Get state at the target block
        let state_provider = self
            .client
            .state_by_block_id(block_id)
            .map_err(internal_err)?;

        // 4. Build a revm State backed by the provider
        let db = StateProviderDatabase::new(state_provider.as_ref());
        let mut state = State::builder()
            .with_database(db)
            .with_bundle_prestate(BundleState::default())
            .with_bundle_update()
            .build();

        // 5. Create the Optimism-aware EVM with our simulation inspector
        let (inspector, inspector_handle) = new_simulation_inspector();
        let mut evm =
            OpEvmFactory::default().create_evm_with_inspector(&mut state, evm_env, inspector);

        // 6. Build the transaction environment
        //    from = entry_point → msg.sender inside the smart account is the EntryPoint
        //    to   = sender      → call the smart account
        //    data = callData    → the UserOp's execution payload
        let gas_limit: u64 = request
            .call_gas_limit
            .and_then(|g| g.try_into().ok())
            .unwrap_or(30_000_000);

        let tx = OpTransaction {
            base: TxEnv {
                caller: request.entry_point,
                kind: TxKind::Call(request.sender),
                data: request.call_data.clone(),
                value: U256::ZERO,
                gas_limit,
                gas_price: 0,
                ..Default::default()
            },
            ..Default::default()
        };

        // 7. Execute
        let result_and_state =
            RethEvm::transact(&mut evm, tx).map_err(|e| internal_err(format!("{e}")))?;

        // 8. Build the response
        let (status, revert_reason, gas_used, logs) = match &result_and_state.result {
            ExecutionResult::Success { gas_used, logs, .. } => {
                (SimulationStatus::Success, None, *gas_used, logs.clone())
            }
            ExecutionResult::Revert { gas_used, output } => {
                let reason = decode_revert_reason(output);
                (SimulationStatus::Revert, Some(reason), *gas_used, vec![])
            }
            ExecutionResult::Halt { gas_used, reason } => {
                let reason_str = format!("{reason:?}");
                (
                    SimulationStatus::Revert,
                    Some(reason_str),
                    *gas_used,
                    vec![],
                )
            }
        };

        // 9. Parse logs into structured asset/approval changes
        let mut asset_changes = parse_asset_changes(&logs);
        let mut approval_changes = parse_approval_changes(&logs);

        // 10. Extract trace and native transfers from inspector
        let trace = inspector_handle.take_trace_entries();
        let native_changes = inspector_handle.take_native_asset_changes();
        asset_changes.extend(native_changes);

        // 11. Resolve on-chain token metadata (name, symbol, decimals) — cached
        resolve_all_metadata(
            &self.client,
            &self.evm_config,
            header.header(),
            block_id,
            &self.metadata_cache,
            &mut asset_changes,
            &mut approval_changes,
        );

        Ok(SimulateUnsignedUserOpResult {
            status,
            revert_reason,
            block_number,
            gas_used: format!("{gas_used:#x}"),
            asset_changes,
            approval_changes,
            trace,
            warnings: vec![],
        })
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Event signatures (keccak256 of canonical event strings)
// ═══════════════════════════════════════════════════════════════════════════════

/// `Transfer(address,address,uint256)` — ERC-20 and ERC-721
const TRANSFER_TOPIC: B256 =
    alloy_primitives::b256!("ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef");

/// `TransferSingle(address,address,address,uint256,uint256)` — ERC-1155
const TRANSFER_SINGLE_TOPIC: B256 =
    alloy_primitives::b256!("c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62");

/// `TransferBatch(address,address,address,uint256[],uint256[])` — ERC-1155
const TRANSFER_BATCH_TOPIC: B256 =
    alloy_primitives::b256!("4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb");

/// `Approval(address,address,uint256)` — ERC-20 and ERC-721
const APPROVAL_TOPIC: B256 =
    alloy_primitives::b256!("8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925");

/// `ApprovalForAll(address,address,bool)` — ERC-721 / ERC-1155
const APPROVAL_FOR_ALL_TOPIC: B256 =
    alloy_primitives::b256!("17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31");

// ═══════════════════════════════════════════════════════════════════════════════
// Log parsing — asset changes
// ═══════════════════════════════════════════════════════════════════════════════

pub fn parse_asset_changes(logs: &[alloy_primitives::Log]) -> Vec<AssetChange> {
    let mut changes = Vec::new();

    for log in logs {
        let topics = log.data.topics();
        if topics.is_empty() {
            continue;
        }

        match topics[0] {
            t if t == TRANSFER_TOPIC => {
                if topics.len() == 4 {
                    // ERC-721: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
                    let from = address_from_topic(topics[1]);
                    let to = address_from_topic(topics[2]);
                    let token_id = U256::from_be_bytes(topics[3].0);
                    changes.push(AssetChange {
                        change_type: AssetType::Erc721,
                        from,
                        to,
                        raw_amount: "1".to_string(),
                        token_id: Some(token_id.to_string()),
                        asset: placeholder_asset(log.address, AssetType::Erc721),
                    });
                } else if topics.len() == 3 && log.data.data.len() >= 32 {
                    // ERC-20: Transfer(address indexed from, address indexed to, uint256 value)
                    let from = address_from_topic(topics[1]);
                    let to = address_from_topic(topics[2]);
                    let amount = U256::from_be_slice(&log.data.data[..32]);
                    changes.push(AssetChange {
                        change_type: AssetType::Erc20,
                        from,
                        to,
                        raw_amount: amount.to_string(),
                        token_id: None,
                        asset: placeholder_asset(log.address, AssetType::Erc20),
                    });
                }
            }
            t if t == TRANSFER_SINGLE_TOPIC
                // ERC-1155: TransferSingle(operator indexed, from indexed, to indexed, id, value)
                // 4 topics: [sig, operator, from, to]; data: [id, value]
                && topics.len() == 4 && log.data.data.len() >= 64 =>
            {
                let from = address_from_topic(topics[2]);
                let to = address_from_topic(topics[3]);
                let id = U256::from_be_slice(&log.data.data[..32]);
                let value = U256::from_be_slice(&log.data.data[32..64]);
                changes.push(AssetChange {
                    change_type: AssetType::Erc1155,
                    from,
                    to,
                    raw_amount: value.to_string(),
                    token_id: Some(id.to_string()),
                    asset: placeholder_asset(log.address, AssetType::Erc1155),
                });
            }
            t if t == TRANSFER_BATCH_TOPIC
                // ERC-1155: TransferBatch(operator indexed, from indexed, to indexed, ids[], values[])
                // 4 topics: [sig, operator, from, to]; data: ABI-encoded arrays
                && topics.len() == 4 =>
            {
                let from = address_from_topic(topics[2]);
                let to = address_from_topic(topics[3]);
                if let Some(pairs) = decode_batch_transfer_data(&log.data.data) {
                    for (id, value) in pairs {
                        changes.push(AssetChange {
                            change_type: AssetType::Erc1155,
                            from,
                            to,
                            raw_amount: value.to_string(),
                            token_id: Some(id.to_string()),
                            asset: placeholder_asset(log.address, AssetType::Erc1155),
                        });
                    }
                }
            }
            _ => {}
        }
    }

    changes
}

/// Decode ABI-encoded `(uint256[], uint256[])` from TransferBatch data.
fn decode_batch_transfer_data(data: &[u8]) -> Option<Vec<(U256, U256)>> {
    // ABI: offset_ids (32) | offset_values (32) | ids_len (32) | ids... | values_len (32) | values...
    if data.len() < 128 {
        return None;
    }

    let ids_offset = U256::from_be_slice(&data[..32]).try_into().ok()?;
    let values_offset: usize = U256::from_be_slice(&data[32..64]).try_into().ok()?;

    let ids_len: usize = U256::from_be_slice(data.get(ids_offset..ids_offset + 32)?)
        .try_into()
        .ok()?;
    let values_len: usize = U256::from_be_slice(data.get(values_offset..values_offset + 32)?)
        .try_into()
        .ok()?;

    if ids_len != values_len {
        return None;
    }

    let mut pairs = Vec::with_capacity(ids_len);
    for i in 0..ids_len {
        let id_start = ids_offset + 32 + i * 32;
        let val_start = values_offset + 32 + i * 32;
        let id = U256::from_be_slice(data.get(id_start..id_start + 32)?);
        let value = U256::from_be_slice(data.get(val_start..val_start + 32)?);
        pairs.push((id, value));
    }

    Some(pairs)
}

// ═══════════════════════════════════════════════════════════════════════════════
// Log parsing — approval changes
// ═══════════════════════════════════════════════════════════════════════════════

pub fn parse_approval_changes(logs: &[alloy_primitives::Log]) -> Vec<ApprovalChange> {
    let mut changes = Vec::new();

    for log in logs {
        let topics = log.data.topics();
        if topics.is_empty() {
            continue;
        }

        match topics[0] {
            t if t == APPROVAL_TOPIC => {
                if topics.len() == 3 && log.data.data.len() >= 32 {
                    // ERC-20: Approval(owner, spender, value)
                    let owner = address_from_topic(topics[1]);
                    let spender = address_from_topic(topics[2]);
                    let amount = U256::from_be_slice(&log.data.data[..32]);
                    changes.push(ApprovalChange {
                        owner,
                        spender,
                        raw_amount: amount.to_string(),
                        is_approved_for_all: false,
                        asset: placeholder_asset(log.address, AssetType::Erc20),
                    });
                } else if topics.len() == 4 {
                    // ERC-721: Approval(owner, approved, tokenId)
                    // Not a spending approval in the ERC-20 sense — skip or handle differently.
                    // The spec focuses on Approval events, so include it.
                    let owner = address_from_topic(topics[1]);
                    let spender = address_from_topic(topics[2]);
                    changes.push(ApprovalChange {
                        owner,
                        spender,
                        raw_amount: "1".to_string(),
                        is_approved_for_all: false,
                        asset: placeholder_asset(log.address, AssetType::Erc721),
                    });
                }
            }
            t if t == APPROVAL_FOR_ALL_TOPIC && topics.len() == 3 => {
                let owner = address_from_topic(topics[1]);
                let operator = address_from_topic(topics[2]);
                // ABI: bool approved is encoded as 32 bytes, last byte != 0 means true
                let approved = log.data.data.last().is_some_and(|&b| b != 0);
                changes.push(ApprovalChange {
                    owner,
                    spender: operator,
                    raw_amount: if approved {
                        U256::MAX.to_string()
                    } else {
                        "0".to_string()
                    },
                    is_approved_for_all: approved,
                    asset: placeholder_asset(log.address, AssetType::Erc721),
                });
            }
            _ => {}
        }
    }

    changes
}

// ═══════════════════════════════════════════════════════════════════════════════
// Revert reason decoding
// ═══════════════════════════════════════════════════════════════════════════════

/// Decode revert data into a human-readable string.
/// Handles `Error(string)` (0x08c379a0) and `Panic(uint256)` (0x4e487b71).
pub fn decode_revert_reason(output: &Bytes) -> String {
    if output.len() < 4 {
        return format!("0x{}", hex::encode(output.as_ref()));
    }

    let selector = &output[..4];

    // Error(string) — 0x08c379a0
    if selector == [0x08, 0xc3, 0x79, 0xa0] && output.len() >= 68 {
        let offset: usize = U256::from_be_slice(&output[4..36]).try_into().unwrap_or(0);
        let abs_offset = 4 + offset;
        if abs_offset + 32 <= output.len() {
            let len: usize = U256::from_be_slice(&output[abs_offset..abs_offset + 32])
                .try_into()
                .unwrap_or(0);
            let str_start = abs_offset + 32;
            if str_start + len <= output.len()
                && let Ok(s) = std::str::from_utf8(&output[str_start..str_start + len])
            {
                return s.to_string();
            }
        }
    }

    // Panic(uint256) — 0x4e487b71
    if selector == [0x4e, 0x48, 0x7b, 0x71] && output.len() >= 36 {
        let code = U256::from_be_slice(&output[4..36]);
        let reason = match code.try_into().unwrap_or(0xFFu64) {
            0x00 => "generic compiler panic",
            0x01 => "assertion failed",
            0x11 => "arithmetic overflow/underflow",
            0x12 => "division by zero",
            0x21 => "invalid enum value",
            0x22 => "invalid storage byte array",
            0x31 => "pop on empty array",
            0x32 => "array index out of bounds",
            0x41 => "out of memory",
            0x51 => "uninitialized function pointer",
            _ => "unknown panic",
        };
        return format!("Panic({reason})");
    }

    format!("0x{}", hex::encode(output.as_ref()))
}

// ═══════════════════════════════════════════════════════════════════════════════
// Selector-to-name mapping
// ═══════════════════════════════════════════════════════════════════════════════

/// Best-effort decode of a 4-byte function selector to a human-readable name.
pub fn selector_to_name(selector: [u8; 4]) -> Option<&'static str> {
    match selector {
        // ERC-20
        [0xa9, 0x05, 0x9c, 0xbb] => Some("transfer"),
        [0x23, 0xb8, 0x72, 0xdd] => Some("transferFrom"),
        [0x09, 0x5e, 0xa7, 0xb3] => Some("approve"),
        // ERC-721
        [0x42, 0x84, 0x2e, 0x0e] => Some("safeTransferFrom"),
        [0xb8, 0x8d, 0x4f, 0xde] => Some("safeTransferFrom"),
        [0xa2, 0x2c, 0xb4, 0x65] => Some("setApprovalForAll"),
        // ERC-1155
        [0xf2, 0x42, 0x43, 0x2a] => Some("safeTransferFrom"),
        [0x2e, 0xb2, 0xc2, 0xd6] => Some("safeBatchTransferFrom"),
        // Multicall / execute
        [0xb6, 0x1d, 0x27, 0xf6] => Some("execute"),
        [0x51, 0x94, 0x54, 0x47] => Some("executeBatch"),
        [0x8d, 0x80, 0xff, 0x0a] => Some("multiSend"),
        // Safe admin methods (flagged by backend as forbidden)
        [0x0d, 0x58, 0x2f, 0x13] => Some("addOwnerWithThreshold"),
        [0xf8, 0xdc, 0x5d, 0xd9] => Some("removeOwner"),
        [0xe3, 0x18, 0xb5, 0x2b] => Some("swapOwner"),
        [0x69, 0x4e, 0x80, 0xc3] => Some("changeThreshold"),
        [0x61, 0x0b, 0x59, 0x25] => Some("enableModule"),
        [0xe0, 0x09, 0xcf, 0xde] => Some("disableModule"),
        [0xe1, 0x9a, 0x9d, 0xd9] => Some("setGuard"),
        [0xf0, 0x8a, 0x03, 0x23] => Some("setFallbackHandler"),
        [0xe3, 0x19, 0xf3, 0x23] => Some("setModuleGuard"),
        [0xb6, 0x31, 0x28, 0x05] => Some("setup"),
        // Permit2
        [0x87, 0x51, 0x7c, 0x45] => Some("permit"),
        _ => None,
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Token metadata resolution
// ═══════════════════════════════════════════════════════════════════════════════

/// Well-known ERC-20 function selectors for metadata.
const NAME_SELECTOR: [u8; 4] = [0x06, 0xfd, 0xde, 0x03]; // name()
const SYMBOL_SELECTOR: [u8; 4] = [0x95, 0xd8, 0x9b, 0x41]; // symbol()
const DECIMALS_SELECTOR: [u8; 4] = [0x31, 0x3c, 0xe5, 0x67]; // decimals()

/// Resolve on-chain metadata (name, symbol, decimals) for a token contract.
/// Uses the pre-simulation state via fresh EVM calls.
fn resolve_metadata_with_evm<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    token: Address,
    asset_type: AssetType,
) -> AssetInfo
where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    let name = evm_call_string(client, evm_config, header, block_id, token, &NAME_SELECTOR)
        .unwrap_or_default();
    let symbol = evm_call_string(
        client,
        evm_config,
        header,
        block_id,
        token,
        &SYMBOL_SELECTOR,
    )
    .unwrap_or_default();
    let decimals = evm_call_u8(
        client,
        evm_config,
        header,
        block_id,
        token,
        &DECIMALS_SELECTOR,
    )
    .unwrap_or(0);

    AssetInfo {
        address: Some(token),
        symbol,
        name,
        decimals,
        asset_type,
    }
}

/// Execute a view call that returns a string (ABI-encoded).
fn evm_call_string<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    to: Address,
    selector: &[u8; 4],
) -> Option<String>
where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    let output = evm_static_call(client, evm_config, header, block_id, to, selector)?;
    decode_abi_string(&output)
}

/// Execute a view call that returns a uint8.
fn evm_call_u8<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    to: Address,
    selector: &[u8; 4],
) -> Option<u8>
where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    let output = evm_static_call(client, evm_config, header, block_id, to, selector)?;
    if output.len() >= 32 {
        Some(output[31])
    } else {
        None
    }
}

/// Low-level: execute a simple static call and return raw output bytes.
fn evm_static_call<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    to: Address,
    selector: &[u8; 4],
) -> Option<Bytes>
where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    let evm_env = evm_config.evm_env(header).ok()?;
    let state_provider = client.state_by_block_id(block_id).ok()?;
    let db = StateProviderDatabase::new(state_provider.as_ref());
    let mut state = State::builder()
        .with_database(db)
        .with_bundle_prestate(BundleState::default())
        .with_bundle_update()
        .build();

    let mut evm = OpEvmFactory::default().create_evm(&mut state, evm_env);

    let tx = OpTransaction {
        base: TxEnv {
            caller: Address::ZERO,
            kind: TxKind::Call(to),
            data: Bytes::copy_from_slice(selector),
            value: U256::ZERO,
            gas_limit: 100_000,
            gas_price: 0,
            ..Default::default()
        },
        ..Default::default()
    };

    let result = RethEvm::transact(&mut evm, tx).ok()?;
    match result.result {
        ExecutionResult::Success {
            output: Output::Call(data),
            ..
        } => Some(data),
        _ => None,
    }
}

/// Decode an ABI-encoded string from raw bytes.
fn decode_abi_string(data: &[u8]) -> Option<String> {
    if data.len() < 64 {
        return None;
    }
    let offset: usize = U256::from_be_slice(&data[..32]).try_into().ok()?;
    if offset + 32 > data.len() {
        return None;
    }
    let len: usize = U256::from_be_slice(&data[offset..offset + 32])
        .try_into()
        .ok()?;
    let str_start = offset + 32;
    if str_start + len > data.len() {
        return None;
    }
    String::from_utf8(data[str_start..str_start + len].to_vec()).ok()
}

/// Resolve metadata for all unique token addresses, using a persistent cache.
fn resolve_all_metadata<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    cache: &MetadataCache,
    asset_changes: &mut [AssetChange],
    approval_changes: &mut [ApprovalChange],
) where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    // Collect unique addresses that need resolution (not in cache and not yet resolved).
    let mut to_resolve: Vec<(Address, AssetType)> = Vec::new();

    {
        let cache_guard = cache.lock().unwrap();
        let mut seen_this_call = std::collections::HashSet::new();

        for change in asset_changes.iter() {
            if let Some(addr) = change.asset.address
                && change.asset.symbol.is_empty()
                && !cache_guard.contains_key(&addr)
                && seen_this_call.insert(addr)
            {
                to_resolve.push((addr, change.asset.asset_type));
            }
        }
        for change in approval_changes.iter() {
            if let Some(addr) = change.asset.address
                && change.asset.symbol.is_empty()
                && !cache_guard.contains_key(&addr)
                && seen_this_call.insert(addr)
            {
                to_resolve.push((addr, change.asset.asset_type));
            }
        }
    }

    // Resolve missing metadata via EVM calls and insert into cache
    if !to_resolve.is_empty() {
        let mut cache_guard = cache.lock().unwrap();
        for (addr, asset_type) in &to_resolve {
            let info =
                resolve_metadata_with_evm(client, evm_config, header, block_id, *addr, *asset_type);
            cache_guard.insert(*addr, info);
        }
    }

    // Apply cached metadata to all changes
    let cache_guard = cache.lock().unwrap();
    for change in asset_changes.iter_mut() {
        if let Some(addr) = change.asset.address
            && let Some(info) = cache_guard.get(&addr)
        {
            change.asset = info.clone();
        }
    }
    for change in approval_changes.iter_mut() {
        if let Some(addr) = change.asset.address
            && let Some(info) = cache_guard.get(&addr)
        {
            change.asset = info.clone();
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════════

fn address_from_topic(topic: B256) -> Address {
    Address::from_slice(&topic[12..])
}

/// Placeholder asset info — metadata will be resolved in a later step.
fn placeholder_asset(contract: Address, asset_type: AssetType) -> AssetInfo {
    AssetInfo {
        address: Some(contract),
        symbol: String::new(),
        name: String::new(),
        decimals: 0,
        asset_type,
    }
}

fn internal_err(msg: impl std::fmt::Display) -> jsonrpsee::types::ErrorObjectOwned {
    jsonrpsee::types::ErrorObjectOwned::owned(
        jsonrpsee::types::error::INTERNAL_ERROR_CODE,
        msg.to_string(),
        None::<String>,
    )
}
