use alloy_consensus::BlockHeader;
use alloy_op_evm::{OpEvmFactory, OpTx};
use alloy_primitives::{Address, B256, Bytes, U256};
use alloy_rpc_types::{BlockId, BlockNumberOrTag};
use jsonrpsee::{
    core::{RpcResult, async_trait},
    proc_macros::rpc,
};
use lru::LruCache;
use op_revm::OpTransaction;
use reth_evm::{ConfigureEvm, Evm as RethEvm, EvmFactory};
use reth_optimism_evm::OpEvmConfig;
use reth_provider::{BlockReaderIdExt, HeaderProvider, StateProviderFactory};
use reth_revm::{State, database::StateProviderDatabase};
use revm::{
    Inspector,
    context::{
        TxEnv,
        result::{ExecutionResult, Output},
    },
    interpreter::{CallInputs, CallOutcome},
};
use revm_primitives::TxKind;
use serde::{Deserialize, Serialize};
use std::{
    num::NonZeroUsize,
    sync::{Arc, Mutex},
};

// ═══════════════════════════════════════════════════════════════════════════════
// Request types
// ═══════════════════════════════════════════════════════════════════════════════

/// Request for `worldchain_simulateUnsignedUserOp`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimulateUnsignedUserOpRequest {
    /// The smart account address to call.
    pub sender: Address,
    /// The encoded execution payload (e.g. `executeUserOp` calldata).
    pub call_data: Bytes,
    /// The ERC-4337 EntryPoint address used as `msg.sender` in the simulation.
    pub entry_point: Address,
    /// Optional gas limit for the simulated call. Defaults to `MAX_SIMULATION_GAS`.
    /// Must not exceed `MAX_SIMULATION_GAS`.
    #[serde(default)]
    pub call_gas_limit: Option<U256>,
}

/// Maximum gas limit accepted for a simulated call.
pub const MAX_SIMULATION_GAS: u64 = 8_000_000;

// ═══════════════════════════════════════════════════════════════════════════════
// Response types
// ═══════════════════════════════════════════════════════════════════════════════

/// The standard a token/asset conforms to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AssetType {
    Native,
    Erc20,
    Erc721,
    Erc1155,
}

/// Token/asset metadata resolved from on-chain state.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetInfo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<Address>,
    pub symbol: String,
    pub name: String,
    pub decimals: u8,
    #[serde(rename = "type")]
    pub asset_type: AssetType,
}

/// A discrete asset transfer detected during simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetChange {
    #[serde(rename = "type")]
    pub change_type: AssetType,
    pub from: Address,
    pub to: Address,
    pub raw_amount: String,
    pub token_id: Option<String>,
    pub asset: AssetInfo,
}

/// An ERC-20/721/1155 token approval detected during simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExposureChange {
    pub owner: Address,
    pub spender: Address,
    pub raw_amount: String,
    pub is_approved_for_all: bool,
    pub asset: AssetInfo,
}

/// A call made during execution, forming a full stack trace.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TraceEntry {
    pub from: Address,
    pub to: Address,
    pub method: Option<String>,
    pub selector: String,
    pub value: String,
}

/// Severity level for simulation warnings.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum WarningSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// A warning generated by the node during simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimulationWarning {
    pub severity: WarningSeverity,
    pub message: String,
}

/// Outcome of the simulation execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SimulationStatus {
    Success,
    Revert,
}

/// Full response for `worldchain_simulateUnsignedUserOp`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimulateUnsignedUserOpResult {
    pub status: SimulationStatus,
    pub revert_reason: Option<String>,
    pub block_number: u64,
    pub gas_used: String,
    pub asset_changes: Vec<AssetChange>,
    pub exposure_changes: Vec<ExposureChange>,
    pub trace: Vec<TraceEntry>,
    pub warnings: Vec<SimulationWarning>,
}

// ═══════════════════════════════════════════════════════════════════════════════
// Simulation inspector — captures call trace and native ETH transfers
// ═══════════════════════════════════════════════════════════════════════════════

/// Shared state captured by the simulation inspector.
#[derive(Debug, Default)]
struct InspectorState {
    /// Full call stack trace — every CALL/STATICCALL/DELEGATECALL at every depth.
    /// Includes reverted calls so debug consumers can see what was attempted.
    traces: Vec<RawTrace>,
    /// Native ETH transfers from successfully completed call frames only.
    /// Reverted/halted frames don't actually move ETH, so their tentative
    /// entries in `pending_frames` are dropped instead of being committed here.
    native_transfers: Vec<NativeTransfer>,
    /// One entry per active call frame, holding tentative native transfers
    /// recorded on entry. On `call_end` the frame is popped: committed (or
    /// merged into the parent frame) on success, dropped on revert/halt.
    pending_frames: Vec<Vec<NativeTransfer>>,
}

#[derive(Debug)]
struct RawTrace {
    from: Address,
    to: Address,
    selector: [u8; 4],
    value: U256,
}

#[derive(Debug)]
struct NativeTransfer {
    from: Address,
    to: Address,
    value: U256,
}

/// Captures top-level calls made by the smart account and native ETH transfers.
///
/// Uses `Arc<Mutex>` so the caller can read captured data after the EVM consumes
/// the inspector.
#[derive(Debug, Clone, Default)]
pub struct SimulationInspector {
    state: Arc<Mutex<InspectorState>>,
}

/// Handle returned to the caller for reading captured data after execution.
#[derive(Debug, Clone)]
pub struct InspectorHandle {
    state: Arc<Mutex<InspectorState>>,
}

impl InspectorHandle {
    pub fn take_trace_entries(&self) -> Vec<TraceEntry> {
        let state = self.state.lock().unwrap();
        state
            .traces
            .iter()
            .map(|t| {
                let sel = t.selector;
                TraceEntry {
                    from: t.from,
                    to: t.to,
                    method: selector_to_name(sel).map(str::to_string),
                    selector: format!("0x{}", hex::encode(sel)),
                    value: format!("{:#x}", t.value),
                }
            })
            .collect()
    }

    pub fn take_native_asset_changes(&self) -> Vec<AssetChange> {
        let state = self.state.lock().unwrap();
        state
            .native_transfers
            .iter()
            .map(|t| AssetChange {
                change_type: AssetType::Native,
                from: t.from,
                to: t.to,
                raw_amount: t.value.to_string(),
                token_id: None,
                asset: AssetInfo {
                    address: None,
                    symbol: "ETH".to_string(),
                    name: "Ether".to_string(),
                    decimals: 18,
                    asset_type: AssetType::Native,
                },
            })
            .collect()
    }
}

pub fn new_simulation_inspector() -> (SimulationInspector, InspectorHandle) {
    let state = Arc::new(Mutex::new(InspectorState::default()));
    (
        SimulationInspector {
            state: state.clone(),
        },
        InspectorHandle { state },
    )
}

impl<CTX> Inspector<CTX> for SimulationInspector {
    fn call(&mut self, _context: &mut CTX, inputs: &mut CallInputs) -> Option<CallOutcome> {
        let mut state = self.state.lock().unwrap();

        // Record every call at every depth for a full stack trace
        let selector = match &inputs.input {
            revm::interpreter::CallInput::Bytes(b) if b.len() >= 4 => {
                let mut sel = [0u8; 4];
                sel.copy_from_slice(&b[..4]);
                sel
            }
            _ => [0u8; 4],
        };
        let value = inputs.value.transfer().unwrap_or(U256::ZERO);
        state.traces.push(RawTrace {
            from: inputs.caller,
            to: inputs.target_address,
            selector,
            value,
        });

        // Open a new frame for tentative native transfers. If this call frame
        // reverts, `call_end` will drop the frame; only successful frames
        // commit their transfers.
        let mut frame = Vec::new();
        if let Some(value) = inputs.value.transfer()
            && value > U256::ZERO
        {
            frame.push(NativeTransfer {
                from: inputs.caller,
                to: inputs.target_address,
                value,
            });
        }
        state.pending_frames.push(frame);

        None
    }

    fn call_end(
        &mut self,
        _context: &mut CTX,
        _inputs: &CallInputs,
        outcome: &mut CallOutcome,
    ) {
        let mut state = self.state.lock().unwrap();
        let Some(frame) = state.pending_frames.pop() else {
            return;
        };
        if !outcome.instruction_result().is_ok() {
            // Frame reverted/halted — drop its tentative transfers.
            return;
        }
        // Successful frame: bubble transfers up to the parent's tentative list,
        // or commit them as final if this was the outermost frame.
        if let Some(parent) = state.pending_frames.last_mut() {
            parent.extend(frame);
        } else {
            state.native_transfers.extend(frame);
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// RPC trait
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg_attr(not(test), rpc(server, namespace = "worldchain"))]
#[cfg_attr(test, rpc(server, client, namespace = "worldchain"))]
#[async_trait]
pub trait WorldChainSimulateApi {
    /// Simulates an unsigned ERC-4337 v0.7 PackedUserOperation against the
    /// specified block state. Returns asset transfers, approval changes,
    /// decoded trace, and warnings.
    #[method(name = "simulateUnsignedUserOp")]
    async fn simulate_unsigned_user_op(
        &self,
        request: SimulateUnsignedUserOpRequest,
    ) -> RpcResult<SimulateUnsignedUserOpResult>;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Implementation
// ═══════════════════════════════════════════════════════════════════════════════

/// Maximum number of token metadata entries kept across requests.
///
/// Bounded to prevent unbounded memory growth from adversarial UserOps that
/// emit Transfer events from many fresh token contracts.
const METADATA_CACHE_CAPACITY: usize = 1000;

/// Cross-request cache for resolved token metadata. LRU-bounded.
type MetadataCache = Arc<Mutex<LruCache<Address, AssetInfo>>>;

/// Implementation of the `worldchain_simulateUnsignedUserOp` RPC endpoint.
#[derive(Debug, Clone)]
pub struct WorldChainSimulate<Client> {
    client: Client,
    evm_config: OpEvmConfig,
    metadata_cache: MetadataCache,
}

impl<Client> WorldChainSimulate<Client> {
    pub fn new(client: Client, evm_config: OpEvmConfig) -> Self {
        Self {
            client,
            evm_config,
            metadata_cache: Arc::new(Mutex::new(LruCache::new(
                NonZeroUsize::new(METADATA_CACHE_CAPACITY).expect("non-zero capacity"),
            ))),
        }
    }
}

#[async_trait]
impl<Client> WorldChainSimulateApiServer for WorldChainSimulate<Client>
where
    Client: BlockReaderIdExt
        + StateProviderFactory
        + HeaderProvider<Header = alloy_consensus::Header>
        + Clone
        + Send
        + Sync
        + 'static,
{
    async fn simulate_unsigned_user_op(
        &self,
        request: SimulateUnsignedUserOpRequest,
    ) -> RpcResult<SimulateUnsignedUserOpResult> {
        // The simulation does multiple synchronous state-provider reads and a
        // full EVM execution; running it directly on the Tokio reactor thread
        // would block other RPC tasks. Move it to the blocking pool.
        let this = self.clone();
        tokio::task::spawn_blocking(move || this.simulate_blocking(request))
            .await
            .map_err(|e| internal_err(format!("simulation task panicked: {e}")))?
    }
}

impl<Client> WorldChainSimulate<Client>
where
    Client: BlockReaderIdExt
        + StateProviderFactory
        + HeaderProvider<Header = alloy_consensus::Header>,
{
    fn simulate_blocking(
        &self,
        request: SimulateUnsignedUserOpRequest,
    ) -> RpcResult<SimulateUnsignedUserOpResult> {
        // 1. Resolve the latest sealed header. Subsequent lookups go by its
        //    concrete hash so a new block arriving mid-request can't desync
        //    the header from the state we read.
        let header = self
            .client
            .sealed_header_by_id(BlockNumberOrTag::Latest.into())
            .map_err(internal_err)?
            .ok_or_else(|| {
                jsonrpsee::types::ErrorObjectOwned::owned(
                    jsonrpsee::types::error::INVALID_PARAMS_CODE,
                    "Latest block not found",
                    None::<String>,
                )
            })?;
        let block_number = header.number();
        let block_id = BlockId::Hash(header.hash().into());

        // 2. Build the EVM environment from the header (same as eth_call)
        let mut evm_env = self
            .evm_config
            .evm_env(header.header())
            .map_err(internal_err)?;

        // Relax EVM rules to match eth_call semantics: the simulation should
        // succeed regardless of gas pricing, sender balance, or block limits.
        evm_env.cfg_env.disable_block_gas_limit = true;
        evm_env.cfg_env.disable_eip3607 = true;
        evm_env.cfg_env.disable_base_fee = true;

        // 3. Get state at the target block (same as eth_call)
        let state_provider = self
            .client
            .state_by_block_id(block_id)
            .map_err(internal_err)?;

        // 4. Build a revm State backed by the provider — no bundle tracking
        //    needed since we discard post-execution state (same as eth_call).
        let db = StateProviderDatabase::new(state_provider.as_ref());
        let mut state = State::builder().with_database(db).build();

        // 5. Create the Optimism-aware EVM with our simulation inspector
        let (inspector, inspector_handle) = new_simulation_inspector();
        let mut evm =
            OpEvmFactory::default().create_evm_with_inspector(&mut state, evm_env, inspector);

        // 6. Build the transaction environment
        //    from = entry_point → msg.sender inside the smart account is the EntryPoint
        //    to   = sender      → call the smart account
        //    data = callData    → the UserOp's execution payload
        let gas_limit: u64 = match request.call_gas_limit {
            Some(g) => {
                let g: u64 = g.try_into().map_err(|_| {
                    jsonrpsee::types::ErrorObjectOwned::owned(
                        jsonrpsee::types::error::INVALID_PARAMS_CODE,
                        format!("callGasLimit exceeds maximum of {MAX_SIMULATION_GAS}"),
                        None::<String>,
                    )
                })?;
                if g > MAX_SIMULATION_GAS {
                    return Err(jsonrpsee::types::ErrorObjectOwned::owned(
                        jsonrpsee::types::error::INVALID_PARAMS_CODE,
                        format!("callGasLimit exceeds maximum of {MAX_SIMULATION_GAS}"),
                        None::<String>,
                    ));
                }
                g
            }
            None => MAX_SIMULATION_GAS,
        };

        let tx = OpTx(OpTransaction {
            base: TxEnv {
                caller: request.entry_point,
                kind: TxKind::Call(request.sender),
                data: request.call_data.clone(),
                value: U256::ZERO,
                gas_limit,
                gas_price: 0,
                ..Default::default()
            },
            ..Default::default()
        });

        // 7. Execute
        let result_and_state =
            RethEvm::transact(&mut evm, tx).map_err(|e| internal_err(format!("{e}")))?;

        // 8. Build the response
        let (status, revert_reason, gas_used, logs) = match &result_and_state.result {
            ExecutionResult::Success { gas, logs, .. } => {
                (SimulationStatus::Success, None, gas.used(), logs.clone())
            }
            ExecutionResult::Revert { gas, logs, output } => {
                let reason = decode_revert_reason(output);
                (SimulationStatus::Revert, Some(reason), gas.used(), logs.clone())
            }
            ExecutionResult::Halt { gas, logs, reason } => {
                let reason_str = format!("{reason:?}");
                (
                    SimulationStatus::Revert,
                    Some(reason_str),
                    gas.used(),
                    logs.clone(),
                )
            }
        };

        // 9. Parse logs into structured asset/approval changes
        let mut asset_changes = parse_asset_changes(&logs).map_err(|m| {
            jsonrpsee::types::ErrorObjectOwned::owned(
                jsonrpsee::types::error::INVALID_PARAMS_CODE,
                m,
                None::<String>,
            )
        })?;
        let mut exposure_changes = parse_exposure_changes(&logs);

        // 10. Extract trace and native transfers from inspector
        let trace = inspector_handle.take_trace_entries();
        let native_changes = inspector_handle.take_native_asset_changes();
        asset_changes.extend(native_changes);

        // 11. Resolve on-chain token metadata (name, symbol, decimals) — cached
        resolve_all_metadata(
            &self.client,
            &self.evm_config,
            header.header(),
            block_id,
            &self.metadata_cache,
            &mut asset_changes,
            &mut exposure_changes,
        );

        Ok(SimulateUnsignedUserOpResult {
            status,
            revert_reason,
            block_number,
            gas_used: format!("{gas_used:#x}"),
            asset_changes,
            exposure_changes,
            trace,
            warnings: vec![],
        })
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Event signatures (keccak256 of canonical event strings)
// ═══════════════════════════════════════════════════════════════════════════════

/// `Transfer(address,address,uint256)` — ERC-20 and ERC-721
const TRANSFER_TOPIC: B256 =
    alloy_primitives::b256!("ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef");

/// `TransferSingle(address,address,address,uint256,uint256)` — ERC-1155
const TRANSFER_SINGLE_TOPIC: B256 =
    alloy_primitives::b256!("c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62");

/// `TransferBatch(address,address,address,uint256[],uint256[])` — ERC-1155
const TRANSFER_BATCH_TOPIC: B256 =
    alloy_primitives::b256!("4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb");

/// `Approval(address,address,uint256)` — ERC-20 and ERC-721
const APPROVAL_TOPIC: B256 =
    alloy_primitives::b256!("8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925");

/// `ApprovalForAll(address,address,bool)` — ERC-721 / ERC-1155
const APPROVAL_FOR_ALL_TOPIC: B256 =
    alloy_primitives::b256!("17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31");

// ═══════════════════════════════════════════════════════════════════════════════
// Log parsing — asset changes
// ═══════════════════════════════════════════════════════════════════════════════

/// Maximum number of (id, value) pairs accepted in a single ERC-1155 TransferBatch log.
///
/// Bounded to prevent adversarially crafted logs from forcing huge allocations
/// in `decode_batch_transfer_data`.
pub const MAX_BATCH_TRANSFERS: usize = 1000;

pub fn parse_asset_changes(
    logs: &[alloy_primitives::Log],
) -> Result<Vec<AssetChange>, &'static str> {
    let mut changes = Vec::new();

    for log in logs {
        let topics = log.data.topics();
        if topics.is_empty() {
            continue;
        }

        match topics[0] {
            t if t == TRANSFER_TOPIC => {
                if topics.len() == 4 {
                    // ERC-721: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
                    let from = address_from_topic(topics[1]);
                    let to = address_from_topic(topics[2]);
                    let token_id = U256::from_be_bytes(topics[3].0);
                    changes.push(AssetChange {
                        change_type: AssetType::Erc721,
                        from,
                        to,
                        raw_amount: "1".to_string(),
                        token_id: Some(token_id.to_string()),
                        asset: placeholder_asset(log.address, AssetType::Erc721),
                    });
                } else if topics.len() == 3 && log.data.data.len() >= 32 {
                    // ERC-20: Transfer(address indexed from, address indexed to, uint256 value)
                    let from = address_from_topic(topics[1]);
                    let to = address_from_topic(topics[2]);
                    let amount = U256::from_be_slice(&log.data.data[..32]);
                    changes.push(AssetChange {
                        change_type: AssetType::Erc20,
                        from,
                        to,
                        raw_amount: amount.to_string(),
                        token_id: None,
                        asset: placeholder_asset(log.address, AssetType::Erc20),
                    });
                }
            }
            t if t == TRANSFER_SINGLE_TOPIC
                // ERC-1155: TransferSingle(operator indexed, from indexed, to indexed, id, value)
                // 4 topics: [sig, operator, from, to]; data: [id, value]
                && topics.len() == 4 && log.data.data.len() >= 64 =>
            {
                let from = address_from_topic(topics[2]);
                let to = address_from_topic(topics[3]);
                let id = U256::from_be_slice(&log.data.data[..32]);
                let value = U256::from_be_slice(&log.data.data[32..64]);
                changes.push(AssetChange {
                    change_type: AssetType::Erc1155,
                    from,
                    to,
                    raw_amount: value.to_string(),
                    token_id: Some(id.to_string()),
                    asset: placeholder_asset(log.address, AssetType::Erc1155),
                });
            }
            t if t == TRANSFER_BATCH_TOPIC
                // ERC-1155: TransferBatch(operator indexed, from indexed, to indexed, ids[], values[])
                // 4 topics: [sig, operator, from, to]; data: ABI-encoded arrays
                && topics.len() == 4 =>
            {
                let from = address_from_topic(topics[2]);
                let to = address_from_topic(topics[3]);
                if let Some(pairs) = decode_batch_transfer_data(&log.data.data)? {
                    for (id, value) in pairs {
                        changes.push(AssetChange {
                            change_type: AssetType::Erc1155,
                            from,
                            to,
                            raw_amount: value.to_string(),
                            token_id: Some(id.to_string()),
                            asset: placeholder_asset(log.address, AssetType::Erc1155),
                        });
                    }
                }
            }
            _ => {}
        }
    }

    Ok(changes)
}

/// Decode ABI-encoded `(uint256[], uint256[])` from TransferBatch data.
///
/// Returns:
/// - `Ok(Some(pairs))` on successful decode
/// - `Ok(None)` if the log is malformed (callers should silently skip)
/// - `Err(_)` if the encoded length exceeds [`MAX_BATCH_TRANSFERS`] — propagated
///   to the RPC caller rather than skipped, so a malicious log can't both poison
///   simulation results and avoid surfacing.
fn decode_batch_transfer_data(
    data: &[u8],
) -> Result<Option<Vec<(U256, U256)>>, &'static str> {
    // ABI: offset_ids (32) | offset_values (32) | ids_len (32) | ids... | values_len (32) | values...
    if data.len() < 128 {
        return Ok(None);
    }

    let Ok(ids_offset): Result<usize, _> = U256::from_be_slice(&data[..32]).try_into() else {
        return Ok(None);
    };
    let Ok(values_offset): Result<usize, _> = U256::from_be_slice(&data[32..64]).try_into() else {
        return Ok(None);
    };

    let Some(ids_len_slice) = data.get(ids_offset..ids_offset + 32) else {
        return Ok(None);
    };
    let Ok(ids_len): Result<usize, _> = U256::from_be_slice(ids_len_slice).try_into() else {
        return Ok(None);
    };
    let Some(values_len_slice) = data.get(values_offset..values_offset + 32) else {
        return Ok(None);
    };
    let Ok(values_len): Result<usize, _> = U256::from_be_slice(values_len_slice).try_into() else {
        return Ok(None);
    };

    if ids_len != values_len {
        return Ok(None);
    }

    if ids_len > MAX_BATCH_TRANSFERS {
        return Err("erc1155 batch transfer exceeds maximum of 1000 entries");
    }

    let mut pairs = Vec::with_capacity(ids_len);
    for i in 0..ids_len {
        let id_start = ids_offset + 32 + i * 32;
        let val_start = values_offset + 32 + i * 32;
        let Some(id_slice) = data.get(id_start..id_start + 32) else {
            return Ok(None);
        };
        let Some(val_slice) = data.get(val_start..val_start + 32) else {
            return Ok(None);
        };
        pairs.push((U256::from_be_slice(id_slice), U256::from_be_slice(val_slice)));
    }

    Ok(Some(pairs))
}

// ═══════════════════════════════════════════════════════════════════════════════
// Log parsing — approval changes
// ═══════════════════════════════════════════════════════════════════════════════

pub fn parse_exposure_changes(logs: &[alloy_primitives::Log]) -> Vec<ExposureChange> {
    let mut changes = Vec::new();

    for log in logs {
        let topics = log.data.topics();
        if topics.is_empty() {
            continue;
        }

        match topics[0] {
            t if t == APPROVAL_TOPIC => {
                if topics.len() == 3 && log.data.data.len() >= 32 {
                    // ERC-20: Approval(owner, spender, value)
                    let owner = address_from_topic(topics[1]);
                    let spender = address_from_topic(topics[2]);
                    let amount = U256::from_be_slice(&log.data.data[..32]);
                    changes.push(ExposureChange {
                        owner,
                        spender,
                        raw_amount: amount.to_string(),
                        is_approved_for_all: false,
                        asset: placeholder_asset(log.address, AssetType::Erc20),
                    });
                } else if topics.len() == 4 {
                    // ERC-721: Approval(owner, approved, tokenId)
                    // Not a spending approval in the ERC-20 sense — skip or handle differently.
                    // The spec focuses on Approval events, so include it.
                    let owner = address_from_topic(topics[1]);
                    let spender = address_from_topic(topics[2]);
                    changes.push(ExposureChange {
                        owner,
                        spender,
                        raw_amount: "1".to_string(),
                        is_approved_for_all: false,
                        asset: placeholder_asset(log.address, AssetType::Erc721),
                    });
                }
            }
            t if t == APPROVAL_FOR_ALL_TOPIC && topics.len() == 3 => {
                let owner = address_from_topic(topics[1]);
                let operator = address_from_topic(topics[2]);
                // ABI: bool approved is encoded as 32 bytes, last byte != 0 means true
                let approved = log.data.data.last().is_some_and(|&b| b != 0);
                changes.push(ExposureChange {
                    owner,
                    spender: operator,
                    raw_amount: if approved {
                        U256::MAX.to_string()
                    } else {
                        "0".to_string()
                    },
                    is_approved_for_all: approved,
                    asset: placeholder_asset(log.address, AssetType::Erc721),
                });
            }
            _ => {}
        }
    }

    changes
}

// ═══════════════════════════════════════════════════════════════════════════════
// Revert reason decoding
// ═══════════════════════════════════════════════════════════════════════════════

/// Decode revert data into a human-readable string.
/// Handles `Error(string)` (0x08c379a0) and `Panic(uint256)` (0x4e487b71).
pub fn decode_revert_reason(output: &Bytes) -> String {
    if output.len() < 4 {
        return format!("0x{}", hex::encode(output.as_ref()));
    }

    let selector = &output[..4];

    // Error(string) — 0x08c379a0
    if selector == [0x08, 0xc3, 0x79, 0xa0] && output.len() >= 68 {
        let offset: usize = U256::from_be_slice(&output[4..36]).try_into().unwrap_or(0);
        let abs_offset = 4 + offset;
        if abs_offset + 32 <= output.len() {
            let len: usize = U256::from_be_slice(&output[abs_offset..abs_offset + 32])
                .try_into()
                .unwrap_or(0);
            let str_start = abs_offset + 32;
            if str_start + len <= output.len()
                && let Ok(s) = std::str::from_utf8(&output[str_start..str_start + len])
            {
                return s.to_string();
            }
        }
    }

    // Panic(uint256) — 0x4e487b71
    if selector == [0x4e, 0x48, 0x7b, 0x71] && output.len() >= 36 {
        let code = U256::from_be_slice(&output[4..36]);
        let reason = match code.try_into().unwrap_or(0xFFu64) {
            0x00 => "generic compiler panic",
            0x01 => "assertion failed",
            0x11 => "arithmetic overflow/underflow",
            0x12 => "division by zero",
            0x21 => "invalid enum value",
            0x22 => "invalid storage byte array",
            0x31 => "pop on empty array",
            0x32 => "array index out of bounds",
            0x41 => "out of memory",
            0x51 => "uninitialized function pointer",
            _ => "unknown panic",
        };
        return format!("Panic({reason})");
    }

    format!("0x{}", hex::encode(output.as_ref()))
}

// ═══════════════════════════════════════════════════════════════════════════════
// Selector-to-name mapping
// ═══════════════════════════════════════════════════════════════════════════════

/// Best-effort decode of a 4-byte function selector to a human-readable name.
pub fn selector_to_name(selector: [u8; 4]) -> Option<&'static str> {
    match selector {
        // ERC-20
        [0xa9, 0x05, 0x9c, 0xbb] => Some("transfer"),
        [0x23, 0xb8, 0x72, 0xdd] => Some("transferFrom"),
        [0x09, 0x5e, 0xa7, 0xb3] => Some("approve"),
        // ERC-721
        [0x42, 0x84, 0x2e, 0x0e] => Some("safeTransferFrom"),
        [0xb8, 0x8d, 0x4f, 0xde] => Some("safeTransferFrom"),
        [0xa2, 0x2c, 0xb4, 0x65] => Some("setApprovalForAll"),
        // ERC-1155
        [0xf2, 0x42, 0x43, 0x2a] => Some("safeTransferFrom"),
        [0x2e, 0xb2, 0xc2, 0xd6] => Some("safeBatchTransferFrom"),
        // Multicall / execute
        [0xb6, 0x1d, 0x27, 0xf6] => Some("execute"),
        [0x51, 0x94, 0x54, 0x47] => Some("executeBatch"),
        [0x8d, 0x80, 0xff, 0x0a] => Some("multiSend"),
        // Safe admin methods (flagged by backend as forbidden)
        [0x0d, 0x58, 0x2f, 0x13] => Some("addOwnerWithThreshold"),
        [0xf8, 0xdc, 0x5d, 0xd9] => Some("removeOwner"),
        [0xe3, 0x18, 0xb5, 0x2b] => Some("swapOwner"),
        [0x69, 0x4e, 0x80, 0xc3] => Some("changeThreshold"),
        [0x61, 0x0b, 0x59, 0x25] => Some("enableModule"),
        [0xe0, 0x09, 0xcf, 0xde] => Some("disableModule"),
        [0xe1, 0x9a, 0x9d, 0xd9] => Some("setGuard"),
        [0xf0, 0x8a, 0x03, 0x23] => Some("setFallbackHandler"),
        [0xe3, 0x19, 0xf3, 0x23] => Some("setModuleGuard"),
        [0xb6, 0x31, 0x28, 0x05] => Some("setup"),
        // Permit2
        [0x87, 0x51, 0x7c, 0x45] => Some("permit"),
        _ => None,
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Token metadata resolution
// ═══════════════════════════════════════════════════════════════════════════════

/// Well-known ERC-20 function selectors for metadata.
const NAME_SELECTOR: [u8; 4] = [0x06, 0xfd, 0xde, 0x03]; // name()
const SYMBOL_SELECTOR: [u8; 4] = [0x95, 0xd8, 0x9b, 0x41]; // symbol()
const DECIMALS_SELECTOR: [u8; 4] = [0x31, 0x3c, 0xe5, 0x67]; // decimals()

/// Resolve metadata (name, symbol, decimals) for every token in `tokens`
/// against a single shared EVM instance and one state provider.
///
/// Each token previously paid for 3 separate state-provider open + EVM build
/// cycles; this batches all 3·N calls onto the same warm state cache.
fn run_metadata_calls<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    tokens: &[(Address, AssetType)],
) -> Vec<(Address, AssetInfo)>
where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    let Ok(mut evm_env) = evm_config.evm_env(header) else {
        return Vec::new();
    };
    evm_env.cfg_env.disable_block_gas_limit = true;
    evm_env.cfg_env.disable_eip3607 = true;
    evm_env.cfg_env.disable_base_fee = true;

    let Ok(state_provider) = client.state_by_block_id(block_id) else {
        return Vec::new();
    };
    let db = StateProviderDatabase::new(state_provider.as_ref());
    let mut state = State::builder().with_database(db).build();
    let mut evm = OpEvmFactory::default().create_evm(&mut state, evm_env);

    let mut call_view = |to: Address, selector: &[u8; 4]| -> Option<Bytes> {
        let tx = OpTx(OpTransaction {
            base: TxEnv {
                caller: Address::ZERO,
                kind: TxKind::Call(to),
                data: Bytes::copy_from_slice(selector),
                value: U256::ZERO,
                gas_limit: 100_000,
                gas_price: 0,
                ..Default::default()
            },
            ..Default::default()
        });
        match RethEvm::transact(&mut evm, tx).ok()?.result {
            ExecutionResult::Success {
                output: Output::Call(data),
                ..
            } => Some(data),
            _ => None,
        }
    };

    let mut out = Vec::with_capacity(tokens.len());
    for (addr, asset_type) in tokens {
        let name = call_view(*addr, &NAME_SELECTOR)
            .and_then(|b| decode_abi_string(&b))
            .unwrap_or_default();
        let symbol = call_view(*addr, &SYMBOL_SELECTOR)
            .and_then(|b| decode_abi_string(&b))
            .unwrap_or_default();
        let decimals = call_view(*addr, &DECIMALS_SELECTOR)
            .and_then(|b| b.get(31).copied())
            .unwrap_or(0);
        out.push((
            *addr,
            AssetInfo {
                address: Some(*addr),
                symbol,
                name,
                decimals,
                asset_type: *asset_type,
            },
        ));
    }
    out
}

/// Decode an ABI-encoded string from raw bytes.
fn decode_abi_string(data: &[u8]) -> Option<String> {
    if data.len() < 64 {
        return None;
    }
    let offset: usize = U256::from_be_slice(&data[..32]).try_into().ok()?;
    if offset + 32 > data.len() {
        return None;
    }
    let len: usize = U256::from_be_slice(&data[offset..offset + 32])
        .try_into()
        .ok()?;
    let str_start = offset + 32;
    if str_start + len > data.len() {
        return None;
    }
    String::from_utf8(data[str_start..str_start + len].to_vec()).ok()
}

/// Resolve metadata for all unique token addresses, using a persistent cache.
fn resolve_all_metadata<Client>(
    client: &Client,
    evm_config: &OpEvmConfig,
    header: &alloy_consensus::Header,
    block_id: alloy_rpc_types::BlockId,
    cache: &MetadataCache,
    asset_changes: &mut [AssetChange],
    exposure_changes: &mut [ExposureChange],
) where
    Client: StateProviderFactory + HeaderProvider<Header = alloy_consensus::Header>,
{
    // Collect unique addresses that need resolution (not in cache and not yet resolved).
    let mut to_resolve: Vec<(Address, AssetType)> = Vec::new();

    {
        let cache_guard = cache.lock().unwrap();
        let mut seen_this_call = std::collections::HashSet::new();

        for change in asset_changes.iter() {
            if let Some(addr) = change.asset.address
                && change.asset.symbol.is_empty()
                && !cache_guard.contains(&addr)
                && seen_this_call.insert(addr)
            {
                to_resolve.push((addr, change.asset.asset_type));
            }
        }
        for change in exposure_changes.iter() {
            if let Some(addr) = change.asset.address
                && change.asset.symbol.is_empty()
                && !cache_guard.contains(&addr)
                && seen_this_call.insert(addr)
            {
                to_resolve.push((addr, change.asset.asset_type));
            }
        }
    }

    // Resolve missing metadata via a single shared EVM instance — the lock is
    // intentionally not held during the EVM/disk work so concurrent requests
    // can read other entries in parallel.
    if !to_resolve.is_empty() {
        let resolved = run_metadata_calls(client, evm_config, header, block_id, &to_resolve);
        let mut cache_guard = cache.lock().unwrap();
        for (addr, info) in resolved {
            cache_guard.put(addr, info);
        }
    }

    // Apply cached metadata to all changes (`get` bumps LRU recency).
    let mut cache_guard = cache.lock().unwrap();
    for change in asset_changes.iter_mut() {
        if let Some(addr) = change.asset.address
            && let Some(info) = cache_guard.get(&addr)
        {
            change.asset = info.clone();
        }
    }
    for change in exposure_changes.iter_mut() {
        if let Some(addr) = change.asset.address
            && let Some(info) = cache_guard.get(&addr)
        {
            change.asset = info.clone();
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════════

fn address_from_topic(topic: B256) -> Address {
    Address::from_slice(&topic[12..])
}

/// Placeholder asset info — metadata will be resolved in a later step.
fn placeholder_asset(contract: Address, asset_type: AssetType) -> AssetInfo {
    AssetInfo {
        address: Some(contract),
        symbol: String::new(),
        name: String::new(),
        decimals: 0,
        asset_type,
    }
}

fn internal_err(msg: impl std::fmt::Display) -> jsonrpsee::types::ErrorObjectOwned {
    jsonrpsee::types::ErrorObjectOwned::owned(
        jsonrpsee::types::error::INTERNAL_ERROR_CODE,
        msg.to_string(),
        None::<String>,
    )
}
