MEMPOOL_CONFIG_MOUNT = "/mempool_config"
MEMPOOL_CONFIG_MOUNT_PATH = MEMPOOL_CONFIG_MOUNT + "/mempool_config.json"
ENTRYPOINT_CONFIG_MOUNT = "/entrypoint_config"
ENTRYPOINT_CONFIG_MOUNT_PATH = ENTRYPOINT_CONFIG_MOUNT + "/entrypoint_config.json"