[package]
name = "world-chain-test-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
world-chain-builder-rpc.workspace = true
world-chain-builder-node.workspace = true
world-chain-builder-pool.workspace = true
world-chain-builder-flashblocks.workspace = true
world-chain-test.workspace = true

rollup-boost.workspace = true

reth.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-primitives.workspace = true
reth-optimism-node.workspace = true
reth-provider.workspace = true
reth-node-api.workspace = true
reth-e2e-test-utils.workspace = true

alloy-primitives.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types.workspace = true
alloy-consensus.workspace = true

op-alloy-rpc-types-engine.workspace = true
alloy-genesis.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true
revm-primitives.workspace = true

tokio.workspace = true
eyre.workspace = true
tracing.workspace = true
futures.workspace = true
serde_json.workspace = true

[dev-dependencies]
reth-tracing.workspace = true
parking_lot.workspace = true
reth-db.workspace = true
reth-optimism-consensus.workspace = true
reth-optimism-payload-builder.workspace = true
reth-optimism-rpc.workspace = true
alloy-network.workspace = true
