[alias]
xtask = "run --package xtask --"
docs = "doc --workspace --all-features --no-deps"
bench = "bench --package builder --bench coordinator --"
bench-save = "bench --package builder --bench coordinator -- --save-baseline"
bench-cmp = "bench --package builder --bench coordinator -- --baseline main --save-baseline pr"
prof-build = "build --profile profiling --features jemalloc --bin world-chain"
prof-bench = "bench --profile profiling --package world-chain-builder --bench coordinator"

[env]
DEBUG = "info,flashblocks=debug,world_chain=info"
TRACE = "info,flashblocks=trace,world_chain=trace,engine::tree=trace"
RUST_BACKTRACE = { value = "full", force = false }
