[alias]
xtask = "run --package xtask --"
docs = "doc --workspace --all-features --no-deps"
b = "bench --package world-chain-builder --bench coordinator --"
bs = "bench --package world-chain-builder --bench coordinator -- --save-baseline"
bc = "bench --package world-chain-builder --bench coordinator -- --baseline main --save-baseline pr"

[env]
DEBUG = "info,flashblocks=debug,world_chain=info"
TRACE = "info,flashblocks=trace,world_chain=trace,engine::tree=trace"
