//! Wire protocol shared by the Nitro host and the in-enclave guest binary.
//!
//! Framing is intentionally trivial: each message is `u32` big-endian length followed by a
//! CBOR-encoded [`EnclaveRequest`] or [`EnclaveResponse`]. We deliberately avoid using rkyv
//! for the outer envelope so that the protocol stays decoupled from the inner witness format
//! and can be evolved (versioned) without re-generating archived layouts. The inner witness
//! payload is rkyv-encoded [`WorldRangeWitnessData`] because that is what the SP1 range
//! program already consumes.

use alloy_primitives::B256;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use world_chain_proof_core::boot::BootInfoStruct;

/// Current protocol version. Bumped whenever the wire format changes incompatibly.
pub const PROTOCOL_VERSION: u32 = 3;

/// Default vsock port the enclave binary listens on.
pub const DEFAULT_VSOCK_PORT: u32 = 5005;

/// Maximum frame size accepted on the wire (256 MiB).
pub const MAX_FRAME_BYTES: u32 = 256 * 1024 * 1024;

/// Requests the host can send to the enclave.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnclaveRequest {
    /// Prove a single range transition.
    Range {
        /// Protocol version the host expects.
        version: u32,
        /// rkyv-serialized `WorldRangeWitnessData`.
        witness_rkyv: Vec<u8>,
        /// Optional host-computed boot info the enclave must match before signing.
        expected_boot_info: Option<BootInfoStruct>,
        /// 32-byte random nonce generated by the host. The enclave passes it to the NSM
        /// so it is embedded in the signed attestation payload, preventing replay attacks.
        nonce: [u8; 32],
    },
    /// Request an NSM attestation document that embeds the enclave's ephemeral public key.
    ///
    /// Used during one-time registration: the host can verify the attestation doc to learn
    /// the enclave's current secp256k1 public key and trust it for subsequent proof signatures.
    PublicKey {
        /// 32-byte random nonce for replay protection (see `Range::nonce`).
        nonce: [u8; 32],
    },
    /// Request a bare NSM attestation document without running any proof.
    ///
    /// Used for CertManager pre-warm: operators need a real attestation document from
    /// a running enclave so the AWS Nitro CA cert chain can be extracted and registered
    /// on L1 before any `registerKey` call can succeed.
    GetAttestation,
}

/// Responses the enclave can return to the host.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnclaveResponse {
    /// Successful range proof.
    Range {
        /// Boot info committed by the enclave.
        boot_info: BootInfoStruct,
        /// `COSE_Sign1` attestation document bytes from the NSM device.
        attestation_doc: Vec<u8>,
        /// 65-byte recoverable secp256k1 signature over
        /// `keccak256(l2_post_root || l2_block_number_be || rollup_config_hash)`.
        ///
        /// The signing key is the enclave's ephemeral keypair, whose public key is
        /// certified by the NSM attestation document via [`EnclaveRequest::PublicKey`].
        signature: Vec<u8>,
    },
    /// NSM attestation document that embeds the enclave's ephemeral secp256k1 public key.
    ///
    /// Returned in response to [`EnclaveRequest::PublicKey`]. The host can verify the
    /// document and extract `public_key` to trust subsequent proof signatures.
    Attestation {
        /// `COSE_Sign1` attestation document bytes. The `public_key` field inside the
        /// document holds the compressed SEC1 encoding of the enclave's secp256k1 key.
        attestation_doc: Vec<u8>,
        /// Compressed SEC1 encoding of the enclave's ephemeral secp256k1 public key
        /// (33 bytes). Included at the top level for convenient extraction without
        /// full document parsing.
        public_key: Vec<u8>,
    },
    /// Bare attestation document returned in response to [`EnclaveRequest::GetAttestation`].
    ///
    /// Contains only the raw `COSE_Sign1` bytes — no proof payload, no public key extraction.
    BareAttestation {
        /// `COSE_Sign1` attestation document bytes from the NSM device.
        attestation_doc: Vec<u8>,
    },
    /// Enclave-side error. The host treats this as a permanent failure for the request.
    Error {
        /// Human-readable error message produced inside the enclave.
        message: String,
    },
}

/// Computes the 32-byte `user_data` that the enclave embeds in the attestation request when
/// signing a range proof. Binding this commits the attestation to the exact transition.
///
/// `SHA256( l2_pre_root || l2_post_root || l2_block_number_be || rollup_config_hash )`
#[must_use]
pub fn range_user_data(boot_info: &BootInfoStruct) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(boot_info.l2PreRoot.as_slice());
    hasher.update(boot_info.l2PostRoot.as_slice());
    hasher.update(boot_info.l2BlockNumber.to_be_bytes());
    hasher.update(boot_info.rollupConfigHash.as_slice());
    let out = hasher.finalize();
    let mut user_data = [0u8; 32];
    user_data.copy_from_slice(out.as_slice());
    user_data
}

/// Writes a length-prefixed CBOR frame.
pub async fn write_frame<W, T>(writer: &mut W, value: &T) -> Result<(), FrameError>
where
    W: AsyncWriteExt + Unpin,
    T: Serialize,
{
    let mut buf = Vec::with_capacity(1024);
    ciborium::into_writer(value, &mut buf).map_err(|err| FrameError::Encode(err.to_string()))?;
    let len: u32 = buf
        .len()
        .try_into()
        .map_err(|_| FrameError::FrameTooLarge(buf.len()))?;
    if len > MAX_FRAME_BYTES {
        return Err(FrameError::FrameTooLarge(buf.len()));
    }
    writer.write_all(&len.to_be_bytes()).await?;
    writer.write_all(&buf).await?;
    writer.flush().await?;
    Ok(())
}

/// Reads a length-prefixed CBOR frame.
pub async fn read_frame<R, T>(reader: &mut R) -> Result<T, FrameError>
where
    R: AsyncReadExt + Unpin,
    T: for<'de> Deserialize<'de>,
{
    let mut len_bytes = [0u8; 4];
    reader.read_exact(&mut len_bytes).await?;
    let len = u32::from_be_bytes(len_bytes);
    if len > MAX_FRAME_BYTES {
        return Err(FrameError::FrameTooLarge(len as usize));
    }
    let mut buf = vec![0u8; len as usize];
    reader.read_exact(&mut buf).await?;
    let value =
        ciborium::from_reader(buf.as_slice()).map_err(|err| FrameError::Decode(err.to_string()))?;
    Ok(value)
}

/// Errors raised by the wire-framing helpers.
#[derive(Debug, thiserror::Error)]
pub enum FrameError {
    /// IO error reading or writing the underlying transport.
    #[error("vsock io error: {0}")]
    Io(#[from] std::io::Error),
    /// CBOR encoding failed.
    #[error("frame encode failed: {0}")]
    Encode(String),
    /// CBOR decoding failed.
    #[error("frame decode failed: {0}")]
    Decode(String),
    /// Frame exceeds the maximum allowed size.
    #[error("frame too large: {0} bytes")]
    FrameTooLarge(usize),
}

/// Computes the 32-byte commitment the enclave signs with its ephemeral secp256k1 key.
///
/// `keccak256( l2_post_root || l2_block_number_be || rollup_config_hash )`
///
/// Unlike [`range_user_data`] (which uses SHA-256 and includes `l2_pre_root`), this
/// commitment uses keccak256 for EVM-native verifiability and omits `l2_pre_root` so it
/// can be reconstructed from only the minimal post-state fields.
#[must_use]
pub fn signing_commitment(boot_info: &BootInfoStruct) -> [u8; 32] {
    let mut buf = Vec::with_capacity(32 + 8 + 32);
    buf.extend_from_slice(boot_info.l2PostRoot.as_slice());
    buf.extend_from_slice(&boot_info.l2BlockNumber.to_be_bytes());
    buf.extend_from_slice(boot_info.rollupConfigHash.as_slice());
    *alloy_primitives::keccak256(&buf)
}

/// Hashes an arbitrary byte slice and returns it as a 32-byte `B256`.
#[must_use]
pub fn sha256_b256(bytes: &[u8]) -> B256 {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    B256::from_slice(hasher.finalize().as_ref())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::B256;

    fn boot_info() -> BootInfoStruct {
        BootInfoStruct {
            l1Head: B256::from([1; 32]),
            l2PreRoot: B256::from([2; 32]),
            l2PostRoot: B256::from([3; 32]),
            l2BlockNumber: 42,
            rollupConfigHash: B256::from([4; 32]),
        }
    }

    #[test]
    fn range_user_data_is_deterministic() {
        let a = range_user_data(&boot_info());
        let b = range_user_data(&boot_info());
        assert_eq!(a, b);
    }

    #[test]
    fn range_user_data_depends_on_post_root() {
        let mut bi = boot_info();
        let original = range_user_data(&bi);
        bi.l2PostRoot = B256::from([9; 32]);
        let mutated = range_user_data(&bi);
        assert_ne!(original, mutated);
    }
}
