//! Wire protocol shared by the Nitro host and the in-enclave guest binary.
//!
//! Framing is intentionally trivial: each message is `u32` big-endian length followed by a
//! CBOR-encoded [`EnclaveRequest`] or [`EnclaveResponse`]. We deliberately avoid using rkyv
//! for the outer envelope so that the protocol stays decoupled from the inner witness format
//! and can be evolved (versioned) without re-generating archived layouts. The inner witness
//! payload is rkyv-encoded [`WorldRangeWitnessData`] because that is what the SP1 range
//! program already consumes.

use alloy_primitives::B256;
use alloy_sol_types::SolValue;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use world_chain_proof_core::boot::TransitionPublicValues;

/// Current protocol version. Bumped whenever the wire format changes incompatibly.
pub const PROTOCOL_VERSION: u32 = 5;

/// Default vsock port the enclave binary listens on.
pub const DEFAULT_VSOCK_PORT: u32 = 5005;

/// Maximum frame size accepted on the wire (256 MiB).
pub const MAX_FRAME_BYTES: u32 = 256 * 1024 * 1024;

/// Requests the host can send to the enclave.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnclaveRequest {
    /// Prove a single range transition.
    Range {
        /// Protocol version the host expects.
        version: u32,
        /// rkyv-serialized `WorldRangeWitnessData`.
        witness_rkyv: Vec<u8>,
        /// Optional host-computed public values the enclave must match before signing.
        expected_transition_public_values: Option<TransitionPublicValues>,
        /// 32-byte random nonce generated by the host. The enclave passes it to the NSM
        /// so it is embedded in the signed attestation payload, preventing replay attacks.
        nonce: [u8; 32],
    },
    /// Request an NSM attestation document that embeds the enclave's ephemeral public key.
    ///
    /// Used during one-time registration: the host can verify the attestation doc to learn
    /// the enclave's current secp256k1 public key and trust it for subsequent proof signatures.
    PublicKey {
        /// 32-byte random nonce for replay protection (see `Range::nonce`).
        nonce: [u8; 32],
    },
    /// Request a bare NSM attestation document without running any proof.
    ///
    /// Used for CertManager pre-warm: operators need a real attestation document from
    /// a running enclave so the AWS Nitro CA cert chain can be extracted and registered
    /// on L1 before any `registerKey` call can succeed.
    GetAttestation,
}

/// Responses the enclave can return to the host.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnclaveResponse {
    /// Successful range proof.
    Range {
        /// Transition public values committed by the enclave.
        transition_public_values: TransitionPublicValues,
        /// `COSE_Sign1` attestation document bytes from the NSM device.
        attestation_doc: Vec<u8>,
        /// 65-byte recoverable secp256k1 signature over the ABI-encoded transition public values.
        ///
        /// The signing key is the enclave's ephemeral keypair, whose public key is
        /// certified by the NSM attestation document via [`EnclaveRequest::PublicKey`].
        signature: Vec<u8>,
    },
    /// NSM attestation document that embeds the enclave's ephemeral secp256k1 public key.
    ///
    /// Returned in response to [`EnclaveRequest::PublicKey`]. The host can verify the
    /// document and extract `public_key` to trust subsequent proof signatures.
    Attestation {
        /// `COSE_Sign1` attestation document bytes. The `public_key` field inside the
        /// document holds the compressed SEC1 encoding of the enclave's secp256k1 key.
        attestation_doc: Vec<u8>,
        /// Compressed SEC1 encoding of the enclave's ephemeral secp256k1 public key
        /// (33 bytes). Included at the top level for convenient extraction without
        /// full document parsing.
        public_key: Vec<u8>,
    },
    /// Bare attestation document returned in response to [`EnclaveRequest::GetAttestation`].
    ///
    /// Contains only the raw `COSE_Sign1` bytes — no proof payload, no public key extraction.
    BareAttestation {
        /// `COSE_Sign1` attestation document bytes from the NSM device.
        attestation_doc: Vec<u8>,
    },
    /// Enclave-side error. The host treats this as a permanent failure for the request.
    Error {
        /// Human-readable error message produced inside the enclave.
        message: String,
    },
}

/// Writes a length-prefixed CBOR frame.
pub async fn write_frame<W, T>(writer: &mut W, value: &T) -> Result<(), FrameError>
where
    W: AsyncWriteExt + Unpin,
    T: Serialize,
{
    let mut buf = Vec::with_capacity(1024);
    ciborium::into_writer(value, &mut buf).map_err(|err| FrameError::Encode(err.to_string()))?;
    let len: u32 = buf
        .len()
        .try_into()
        .map_err(|_| FrameError::FrameTooLarge(buf.len()))?;
    if len > MAX_FRAME_BYTES {
        return Err(FrameError::FrameTooLarge(buf.len()));
    }
    writer.write_all(&len.to_be_bytes()).await?;
    writer.write_all(&buf).await?;
    writer.flush().await?;
    Ok(())
}

/// Reads a length-prefixed CBOR frame.
pub async fn read_frame<R, T>(reader: &mut R) -> Result<T, FrameError>
where
    R: AsyncReadExt + Unpin,
    T: for<'de> Deserialize<'de>,
{
    let mut len_bytes = [0u8; 4];
    reader.read_exact(&mut len_bytes).await?;
    let len = u32::from_be_bytes(len_bytes);
    if len > MAX_FRAME_BYTES {
        return Err(FrameError::FrameTooLarge(len as usize));
    }
    let mut buf = vec![0u8; len as usize];
    reader.read_exact(&mut buf).await?;
    let value =
        ciborium::from_reader(buf.as_slice()).map_err(|err| FrameError::Decode(err.to_string()))?;
    Ok(value)
}

/// Errors raised by the wire-framing helpers.
#[derive(Debug, thiserror::Error)]
pub enum FrameError {
    /// IO error reading or writing the underlying transport.
    #[error("vsock io error: {0}")]
    Io(#[from] std::io::Error),
    /// CBOR encoding failed.
    #[error("frame encode failed: {0}")]
    Encode(String),
    /// CBOR decoding failed.
    #[error("frame decode failed: {0}")]
    Decode(String),
    /// Frame exceeds the maximum allowed size.
    #[error("frame too large: {0} bytes")]
    FrameTooLarge(usize),
}

/// Computes the canonical commitment used for attestation and signing.
///
/// `keccak256(abi.encode(TransitionPublicValues))`
#[must_use]
pub fn transition_commitment(transition_public_values: &TransitionPublicValues) -> [u8; 32] {
    *alloy_primitives::keccak256(transition_public_values.abi_encode())
}

/// Hashes an arbitrary byte slice and returns it as a 32-byte `B256`.
#[must_use]
pub fn sha256_b256(bytes: &[u8]) -> B256 {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    B256::from_slice(hasher.finalize().as_ref())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::B256;

    fn transition_public_values() -> TransitionPublicValues {
        TransitionPublicValues {
            l1Head: B256::from([1; 32]),
            l2PreRoot: B256::from([2; 32]),
            l2PreBlockNumber: 41,
            l2PostRoot: B256::from([3; 32]),
            l2PostBlockNumber: 42,
            rollupConfigHash: B256::from([4; 32]),
        }
    }

    #[test]
    fn transition_commitment_is_deterministic() {
        let a = transition_commitment(&transition_public_values());
        let b = transition_commitment(&transition_public_values());
        assert_eq!(a, b);
    }

    #[test]
    fn transition_commitment_depends_on_post_root() {
        let mut transition_public_values = transition_public_values();
        let original = transition_commitment(&transition_public_values);
        transition_public_values.l2PostRoot = B256::from([9; 32]);
        let mutated = transition_commitment(&transition_public_values);
        assert_ne!(original, mutated);
    }

    #[test]
    fn transition_commitment_depends_on_l1_head_and_block_numbers() {
        let original = transition_commitment(&transition_public_values());

        let mut changed_l1_head = transition_public_values();
        changed_l1_head.l1Head = B256::from([9; 32]);
        assert_ne!(original, transition_commitment(&changed_l1_head));

        let mut changed_pre_block = transition_public_values();
        changed_pre_block.l2PreBlockNumber += 1;
        assert_ne!(original, transition_commitment(&changed_pre_block));

        let mut changed_post_block = transition_public_values();
        changed_post_block.l2PostBlockNumber += 1;
        assert_ne!(original, transition_commitment(&changed_post_block));
    }

    #[test]
    fn transition_commitment_hashes_abi_encoded_public_values() {
        let values = transition_public_values();
        assert_eq!(
            transition_commitment(&values),
            *alloy_primitives::keccak256(values.abi_encode())
        );
    }
}
