[package]
name = "flashblocks-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flashblocks-primitives.workspace = true

reth.workspace = true
reth-ethereum.workspace = true
reth-eth-wire.workspace = true
reth-network = { workspace = true }
reth-node-api = { workspace = true }
reth-node-builder = { workspace = true }
reth-transaction-pool = { workspace = true }

ed25519-dalek.workspace = true
metrics.workspace = true
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
eyre.workspace = true
futures = { workspace = true }
tracing.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
chrono.workspace = true
reth-tasks = { workspace = true }

[dev-dependencies]
# Dependencies for network integration tests
reth-storage-api.workspace = true  # For NoopProvider
reth-network-peers.workspace = true  # For PeerId type
async-trait.workspace = true  # For PeerEventsListener trait
tracing-subscriber.workspace = true  # For log capture in tests

# Dependencies for full node integration tests
flashblocks-node.workspace = true  # For FlashblocksNode, FlashblocksNodeBuilder
flashblocks-cli.workspace = true  # For FlashblocksArgs
ed25519-dalek.workspace = true  # For SigningKey
alloy-genesis.workspace = true  # For Genesis
reth-optimism-chainspec.workspace = true  # For OpChainSpecBuilder
reth-node-builder.workspace = true  # For NodeBuilder, Node trait
reth-node-core.workspace = true  # For NetworkArgs, RpcServerArgs
reth-provider.workspace = true  # For BlockchainProvider
reth-tasks.workspace = true  # For TaskExecutor, TaskManager
serde_json.workspace = true  # For parsing genesis.json
