//! The append-only release log: what has shipped, and which measurement sets are approved.
//!
//! Separate from `measurements.lock` on purpose. The lock is derived and can be thrown away
//! and rebuilt; this file is accumulated and its entries are immutable. It also has to answer
//! "which measurement sets are currently approved" at HEAD, because the on-chain allowlist
//! holds a *set* — the previous enclave stays valid while a new one rolls out.

use eyre::eyre::{bail, eyre};
use serde::{Deserialize, Serialize};

use crate::{
    measure::lock::{Lock, Nitro, Sp1},
    release::version::{Bump, Version},
};

/// Path of the release log relative to the repo root.
pub const LOG_PATH: &str = "releases.toml";

/// One shipped release. Carries a full copy of the measurements so readers never have to
/// walk git history, plus the commit that produced them so the copy stays verifiable.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry {
    /// Released version.
    pub version: String,
    /// Commit whose `measurements.lock` this entry was taken from.
    pub commit: String,
    /// SP1 backend measurements.
    pub sp1: Sp1,
    /// Nitro backend measurements.
    pub nitro: Nitro,
}

/// The whole log.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Log {
    /// Newest stable release, or `""` when nothing is stable yet.
    #[serde(default)]
    pub latest_stable: String,
    /// Newest release candidate, or `""` when no rc series is open.
    #[serde(default)]
    pub latest_rc: String,
    /// Every release ever cut, oldest first. Append-only.
    #[serde(default)]
    pub releases: Vec<Entry>,
}

const HEADER: &str = "\
# This file is @generated by `cargo xtask release`. Append-only.
#
# Entries are immutable: CI rejects any diff that changes or removes one. Each entry is a
# copy of `measurements.lock` at the recorded commit, so verifiers and deploy tooling can
# read the approved measurement sets straight from HEAD.
#
# Cut a release with `cargo xtask release --rc` / `--patch` / `--minor` / `--major`, or
# promote the open rc with `cargo xtask release --promote`.
";

impl Log {
    /// Parses a log and checks its pointers resolve.
    pub fn parse(text: &str) -> eyre::Result<Self> {
        let log: Self = toml::from_str(text).map_err(|e| eyre!("{LOG_PATH}: {e}"))?;
        log.validate()?;
        Ok(log)
    }

    /// Renders the log, header comment included.
    pub fn render(&self) -> eyre::Result<String> {
        let body =
            toml::to_string_pretty(self).map_err(|e| eyre!("serialising {LOG_PATH}: {e}"))?;
        Ok(format!("{HEADER}\n{body}"))
    }

    /// Checks every entry is well-formed, versions are unique and ordered, and the pointers
    /// name entries that exist.
    pub fn validate(&self) -> eyre::Result<()> {
        let mut seen: Vec<Version> = Vec::new();
        for entry in &self.releases {
            let version: Version = entry.version.parse()?;
            if seen.contains(&version) {
                bail!("{LOG_PATH}: duplicate entry for {version}");
            }
            if let Some(previous) = seen.last()
                && version <= *previous
            {
                bail!("{LOG_PATH}: {version} is not newer than the preceding entry {previous}");
            }
            Lock {
                version: crate::measure::lock::SCHEMA_VERSION,
                sp1: entry.sp1.clone(),
                nitro: entry.nitro.clone(),
            }
            .validate()?;
            seen.push(version);
        }

        for (name, pointer) in [
            ("latest_stable", &self.latest_stable),
            ("latest_rc", &self.latest_rc),
        ] {
            if pointer.is_empty() {
                continue;
            }
            let version: Version = pointer.parse()?;
            if !seen.contains(&version) {
                bail!("{LOG_PATH}: {name} = {pointer:?} has no matching entry");
            }
            if (name == "latest_stable") == version.is_rc() {
                bail!("{LOG_PATH}: {name} = {pointer:?} has the wrong kind of version");
            }
        }

        Ok(())
    }

    /// Newest stable release, if any.
    pub fn latest_stable_version(&self) -> eyre::Result<Option<Version>> {
        parse_pointer(&self.latest_stable)
    }

    /// Newest open release candidate, if any.
    pub fn latest_rc_version(&self) -> eyre::Result<Option<Version>> {
        parse_pointer(&self.latest_rc)
    }

    /// Appends a release for `lock` at `commit`, deriving the version from `bump`.
    pub fn cut(&mut self, bump: Bump, commit: &str, lock: &Lock) -> eyre::Result<Version> {
        let version = Version::next(
            bump,
            self.latest_stable_version()?,
            self.latest_rc_version()?,
        );
        self.push(version, commit, lock.sp1.clone(), lock.nitro.clone())?;
        Ok(version)
    }

    /// Promotes the open release candidate to stable, carrying its measurements across
    /// unchanged — the point of promotion is that nothing was rebuilt.
    pub fn promote(&mut self) -> eyre::Result<Version> {
        let rc = self
            .latest_rc_version()?
            .ok_or_else(|| eyre!("{LOG_PATH}: no open release candidate to promote"))?;
        let entry = self
            .releases
            .iter()
            .find(|e| e.version == rc.to_string())
            .ok_or_else(|| eyre!("{LOG_PATH}: latest_rc {rc} has no entry"))?
            .clone();

        let version = rc.base();
        self.push(version, &entry.commit, entry.sp1, entry.nitro)?;
        // The rc has been superseded, so close the series rather than leaving a pointer at a
        // version that is no longer the newest thing released.
        self.latest_rc = String::new();
        Ok(version)
    }

    fn push(&mut self, version: Version, commit: &str, sp1: Sp1, nitro: Nitro) -> eyre::Result<()> {
        if let Some(last) = self.releases.last() {
            let previous: Version = last.version.parse()?;
            if version <= previous {
                bail!("refusing to cut {version}: it is not newer than {previous}");
            }
        }
        self.releases.push(Entry {
            version: version.to_string(),
            commit: commit.to_string(),
            sp1,
            nitro,
        });
        if version.is_rc() {
            self.latest_rc = version.to_string();
        } else {
            self.latest_stable = version.to_string();
        }
        self.validate()
    }

    /// Rejects any change to an entry that already exists on the base branch.
    pub fn check_append_only(&self, base: &Self) -> eyre::Result<()> {
        for base_entry in &base.releases {
            match self
                .releases
                .iter()
                .find(|e| e.version == base_entry.version)
            {
                None => bail!(
                    "{LOG_PATH}: entry {} was removed; the log is append-only",
                    base_entry.version
                ),
                Some(entry) if entry != base_entry => bail!(
                    "{LOG_PATH}: entry {} was modified; released entries are immutable",
                    base_entry.version
                ),
                Some(_) => {}
            }
        }
        Ok(())
    }
}

fn parse_pointer(pointer: &str) -> eyre::Result<Option<Version>> {
    if pointer.is_empty() {
        return Ok(None);
    }
    Ok(Some(pointer.parse()?))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::measure::lock::{SCHEMA_VERSION, Sp1Elf};

    const PCR0: &str = "dc0dc88dc8e2aba973679fc9a8381f422e9f49e0e435dc99bdc32aebeeaf12fa2265699bf0ce4bf84fbf3cb35e72549b";
    const TEE_IMAGE_ID: &str = "0xe6bad10605f4bb2df98e45cd5c400f3374a6d629696231e698ee958c81300621";

    fn lock(tag: char) -> Lock {
        Lock {
            version: SCHEMA_VERSION,
            sp1: Sp1 {
                aggregation_vkey: format!("0x{}", tag.to_string().repeat(64)),
                range_vkey_commitment: format!("0x{}", "2".repeat(64)),
                elf: Sp1Elf {
                    aggregation_sha256: "3".repeat(64),
                    range_sha256: "4".repeat(64),
                },
            },
            nitro: Nitro {
                pcr0: PCR0.to_string(),
                pcr1: "5".repeat(96),
                pcr2: "6".repeat(96),
                tee_image_id: TEE_IMAGE_ID.to_string(),
                binary_sha256: "7".repeat(64),
                dockerfile_sha256: "8".repeat(64),
                cli_version: "v1.4.2".to_string(),
            },
        }
    }

    #[test]
    fn cuts_rc_then_promotes_carrying_measurements_across() {
        let mut log = Log::default();
        let rc = log.cut(Bump::Rc, "aaaa", &lock('1')).unwrap();
        assert_eq!(rc.to_string(), "0.0.1-rc.1");
        assert_eq!(log.latest_rc, "0.0.1-rc.1");
        assert_eq!(log.latest_stable, "");

        let stable = log.promote().unwrap();
        assert_eq!(stable.to_string(), "0.0.1");
        assert_eq!(log.latest_stable, "0.0.1");
        // Promotion closes the series: leaving the pointer would name a superseded version.
        assert_eq!(log.latest_rc, "");
        // Promotion must not invent new measurements.
        assert_eq!(log.releases[0].sp1, log.releases[1].sp1);
        assert_eq!(log.releases[0].nitro, log.releases[1].nitro);
        assert_eq!(log.releases[0].commit, log.releases[1].commit);
    }

    #[test]
    fn round_trips_through_toml() {
        let mut log = Log::default();
        log.cut(Bump::Rc, "aaaa", &lock('1')).unwrap();
        log.cut(Bump::Rc, "bbbb", &lock('2')).unwrap();
        let rendered = log.render().unwrap();
        assert_eq!(Log::parse(&rendered).unwrap(), log);
        assert!(rendered.contains("@generated"));
    }

    #[test]
    fn append_only_rejects_removal_and_modification() {
        let mut base = Log::default();
        base.cut(Bump::Rc, "aaaa", &lock('1')).unwrap();

        // Adding on top is fine.
        let mut extended = base.clone();
        extended.cut(Bump::Rc, "bbbb", &lock('2')).unwrap();
        extended.check_append_only(&base).unwrap();

        // Removing a released entry is not.
        let empty = Log::default();
        assert!(empty.check_append_only(&base).is_err());

        // Neither is editing one.
        let mut edited = base.clone();
        edited.releases[0].nitro.pcr2 = "0".repeat(96);
        let err = edited.check_append_only(&base).unwrap_err().to_string();
        assert!(err.contains("immutable"), "got: {err}");
    }

    #[test]
    fn rejects_pointer_without_an_entry() {
        let log = Log {
            latest_stable: "9.9.9".to_string(),
            ..Default::default()
        };
        assert!(log.validate().is_err());
    }

    /// `latest_stable` must never name a prerelease, and `latest_rc` must never name a
    /// stable version — otherwise "what is approved for production" becomes ambiguous.
    #[test]
    fn rejects_pointer_of_the_wrong_kind() {
        let mut log = Log::default();
        log.cut(Bump::Rc, "aaaa", &lock('1')).unwrap();
        let mut bad = log.clone();
        bad.latest_stable = bad.latest_rc.clone();
        assert!(bad.validate().is_err());
    }

    #[test]
    fn rejects_out_of_order_entries() {
        let mut log = Log::default();
        log.cut(Bump::Minor, "aaaa", &lock('1')).unwrap();
        let mut broken = log.clone();
        broken.releases.push(Entry {
            version: "0.0.1".to_string(),
            commit: "bbbb".to_string(),
            sp1: lock('2').sp1,
            nitro: lock('2').nitro,
        });
        assert!(broken.validate().is_err());
    }

    #[test]
    fn rejects_entry_with_bad_measurements() {
        let mut log = Log::default();
        log.cut(Bump::Rc, "aaaa", &lock('1')).unwrap();
        log.releases[0].nitro.tee_image_id = format!("0x{}", "9".repeat(64));
        assert!(log.validate().is_err());
    }
}
