[package]
name = "world-chain-builder-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
reth.workspace = true
reth-optimism-cli.workspace = true
reth-optimism-chainspec.workspace = true
reth-cli.workspace = true

alloy-op-hardforks.workspace = true
alloy-hardforks.workspace = true

alloy-chains.workspace = true
alloy-primitives.workspace = true

eyre.workspace = true
serde_json.workspace = true

[lints]
workspace = true
