//! The `measurements.toml` document: what the proof system commits to at this commit.

use alloy_primitives::keccak256;
use eyre::eyre::{bail, eyre};
use serde::{Deserialize, Serialize};

/// Path of the document relative to the repo root.
pub const PATH: &str = "measurements.toml";

/// Current schema version.
pub const SCHEMA_VERSION: u32 = 1;

/// SP1 guest measurements. The vkeys are a deterministic function of the ELFs.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Sp1 {
    /// Aggregation program verification key.
    pub aggregation_vkey: String,
    /// Range program verification-key commitment.
    pub range_vkey_commitment: String,
    /// SHA-256 of the compiled `world-chain-aggregation` guest ELF.
    pub aggregation_elf_sha256: String,
    /// SHA-256 of the compiled `world-chain-range-ethereum` guest ELF.
    pub range_elf_sha256: String,
}

/// Nitro enclave measurements.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Nitro {
    /// EIF measurement (kernel + cmdline + all ramdisks).
    pub pcr0: String,
    /// Kernel + bootstrap ramdisk measurement, fixed by the nitro-cli build.
    pub pcr1: String,
    /// Application ramdisk measurement.
    pub pcr2: String,
    /// `keccak256(pcr0)` — how the on-chain registry keys enclave images.
    pub tee_image_id: String,
    /// Nix store path of the image the EIF was built from.
    ///
    /// Recorded because it is a content hash of the entire rootfs closure — every library,
    /// not just the binary — which no PCR alone tells you. A PCR that moves while this is
    /// unchanged means the EIF assembly changed, not the image.
    pub image_store_path: String,
    /// nitro-cli tag that supplied the kernel and bootstrap ramdisk.
    pub cli_version: String,
}

/// The whole document.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Measurements {
    /// Schema version, so the format can change without guesswork.
    pub version: u32,
    /// SP1 backend measurements.
    pub sp1: Sp1,
    /// Nitro backend measurements.
    pub nitro: Nitro,
}

const HEADER: &str = "\
# This file is @generated by `just measure`. Do not edit.
#
# What the proof system commits to, rebuilt from source. `just measure --check` rebuilds and
# fails if anything here is stale; CI runs it on every PR that touches a measured crate.
#
# There is no separate release log. A release is the git tag `proofs/vX.Y.Z`, and what it
# shipped is this file at that tag:
#
#     git show proofs/v1.0.0:measurements.toml
#
# Every value here decides which proofs the on-chain verifiers accept. A change here is a
# change to the system's trust anchors — review it as one.
";

impl Measurements {
    /// Parses and validates a document.
    pub fn parse(text: &str) -> eyre::Result<Self> {
        let doc: Self = toml::from_str(text).map_err(|e| eyre!("{PATH}: {e}"))?;
        doc.validate()?;
        Ok(doc)
    }

    /// Renders the document exactly as `measure` writes it.
    pub fn render(&self) -> eyre::Result<String> {
        let body = toml::to_string_pretty(self).map_err(|e| eyre!("serialising {PATH}: {e}"))?;
        Ok(format!("{HEADER}\n{body}"))
    }

    /// Rejects malformed digests and a `tee_image_id` that does not derive from `pcr0`.
    pub fn validate(&self) -> eyre::Result<()> {
        if self.version != SCHEMA_VERSION {
            bail!(
                "{PATH}: schema version {} is not supported (expected {SCHEMA_VERSION})",
                self.version
            );
        }

        for (field, value, nibbles, prefixed) in [
            ("sp1.aggregation_vkey", &self.sp1.aggregation_vkey, 64, true),
            (
                "sp1.range_vkey_commitment",
                &self.sp1.range_vkey_commitment,
                64,
                true,
            ),
            (
                "sp1.aggregation_elf_sha256",
                &self.sp1.aggregation_elf_sha256,
                64,
                false,
            ),
            (
                "sp1.range_elf_sha256",
                &self.sp1.range_elf_sha256,
                64,
                false,
            ),
            ("nitro.pcr0", &self.nitro.pcr0, 96, false),
            ("nitro.pcr1", &self.nitro.pcr1, 96, false),
            ("nitro.pcr2", &self.nitro.pcr2, 96, false),
            ("nitro.tee_image_id", &self.nitro.tee_image_id, 64, true),
        ] {
            check_hex(field, value, nibbles, prefixed)?;
        }

        let derived = derive_tee_image_id(&self.nitro.pcr0)?;
        if derived != self.nitro.tee_image_id {
            bail!(
                "{PATH}: nitro.tee_image_id {} != keccak256(pcr0) = {derived}",
                self.nitro.tee_image_id
            );
        }
        if !self.nitro.image_store_path.starts_with("/nix/store/") {
            bail!(
                "{PATH}: nitro.image_store_path {:?} is not a nix store path",
                self.nitro.image_store_path
            );
        }
        if self.nitro.cli_version.is_empty() {
            bail!("{PATH}: nitro.cli_version is empty");
        }
        Ok(())
    }

    /// Field-by-field difference, for the `--check` failure message.
    pub fn diff(&self, other: &Self) -> Vec<String> {
        let mut out = Vec::new();
        for (field, a, b) in self.fields(other) {
            if a != b {
                out.push(format!("  {field}\n    committed: {a}\n    rebuilt:   {b}"));
            }
        }
        out
    }

    /// Every comparable field, paired with the other document's value.
    ///
    /// One list drives both `diff` and the test that proves `diff` covers the whole struct,
    /// so a field added to the document cannot end up silently unchecked.
    fn fields<'a>(&'a self, other: &'a Self) -> Vec<(&'static str, &'a str, &'a str)> {
        vec![
            (
                "sp1.aggregation_vkey",
                &self.sp1.aggregation_vkey,
                &other.sp1.aggregation_vkey,
            ),
            (
                "sp1.range_vkey_commitment",
                &self.sp1.range_vkey_commitment,
                &other.sp1.range_vkey_commitment,
            ),
            (
                "sp1.aggregation_elf_sha256",
                &self.sp1.aggregation_elf_sha256,
                &other.sp1.aggregation_elf_sha256,
            ),
            (
                "sp1.range_elf_sha256",
                &self.sp1.range_elf_sha256,
                &other.sp1.range_elf_sha256,
            ),
            ("nitro.pcr0", &self.nitro.pcr0, &other.nitro.pcr0),
            ("nitro.pcr1", &self.nitro.pcr1, &other.nitro.pcr1),
            ("nitro.pcr2", &self.nitro.pcr2, &other.nitro.pcr2),
            (
                "nitro.tee_image_id",
                &self.nitro.tee_image_id,
                &other.nitro.tee_image_id,
            ),
            (
                "nitro.image_store_path",
                &self.nitro.image_store_path,
                &other.nitro.image_store_path,
            ),
            (
                "nitro.cli_version",
                &self.nitro.cli_version,
                &other.nitro.cli_version,
            ),
        ]
    }

    /// The document as a flat JSON object, for `jq` in CI and release tooling.
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "aggregation_vkey": self.sp1.aggregation_vkey,
            "range_vkey_commitment": self.sp1.range_vkey_commitment,
            "aggregation_elf_sha256": self.sp1.aggregation_elf_sha256,
            "range_elf_sha256": self.sp1.range_elf_sha256,
            "pcr0": self.nitro.pcr0,
            "pcr1": self.nitro.pcr1,
            "pcr2": self.nitro.pcr2,
            "tee_image_id": self.nitro.tee_image_id,
            "image_store_path": self.nitro.image_store_path,
            "cli_version": self.nitro.cli_version,
        })
    }
}

/// `0x`-prefixed `keccak256(pcr0)`, the identifier the on-chain registry uses.
pub fn derive_tee_image_id(pcr0: &str) -> eyre::Result<String> {
    let bytes = hex::decode(pcr0).map_err(|e| eyre!("pcr0 is not hex: {e}"))?;
    Ok(format!("0x{:x}", keccak256(bytes)))
}

fn check_hex(field: &str, value: &str, nibbles: usize, prefixed: bool) -> eyre::Result<()> {
    let hex = match (prefixed, value.strip_prefix("0x")) {
        (true, Some(rest)) => rest,
        (true, None) => bail!("{PATH}: {field} must be 0x-prefixed"),
        (false, Some(_)) => bail!("{PATH}: {field} must not be 0x-prefixed"),
        (false, None) => value,
    };
    if hex.len() != nibbles
        || !hex
            .bytes()
            .all(|b| b.is_ascii_digit() || b.is_ascii_lowercase() && b <= b'f')
    {
        bail!("{PATH}: {field} must be {nibbles} lowercase hex characters");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A real PCR0 and its keccak256, so the derivation is pinned against a known pair.
    const PCR0: &str = "dc0dc88dc8e2aba973679fc9a8381f422e9f49e0e435dc99bdc32aebeeaf12fa2265699bf0ce4bf84fbf3cb35e72549b";
    const TEE_IMAGE_ID: &str = "0xe6bad10605f4bb2df98e45cd5c400f3374a6d629696231e698ee958c81300621";

    fn doc() -> Measurements {
        Measurements {
            version: SCHEMA_VERSION,
            sp1: Sp1 {
                aggregation_vkey: format!("0x{}", "1".repeat(64)),
                range_vkey_commitment: format!("0x{}", "2".repeat(64)),
                aggregation_elf_sha256: "3".repeat(64),
                range_elf_sha256: "4".repeat(64),
            },
            nitro: Nitro {
                pcr0: PCR0.to_string(),
                pcr1: "5".repeat(96),
                pcr2: "6".repeat(96),
                tee_image_id: TEE_IMAGE_ID.to_string(),
                image_store_path: "/nix/store/aaaa-world-chain-proof-nitro-enclave.tar.gz"
                    .to_string(),
                cli_version: "v1.4.2".to_string(),
            },
        }
    }

    #[test]
    fn tee_image_id_derives_from_pcr0() {
        assert_eq!(derive_tee_image_id(PCR0).unwrap(), TEE_IMAGE_ID);
    }

    #[test]
    fn round_trips_through_toml_keeping_the_generated_banner() {
        let original = doc();
        let rendered = original.render().unwrap();
        assert!(rendered.contains("@generated"));
        assert_eq!(Measurements::parse(&rendered).unwrap(), original);
    }

    #[test]
    fn rejects_tee_image_id_that_does_not_match_pcr0() {
        let mut d = doc();
        d.nitro.tee_image_id = format!("0x{}", "9".repeat(64));
        let err = d.validate().unwrap_err().to_string();
        assert!(err.contains("keccak256(pcr0)"), "{err}");
    }

    #[test]
    fn rejects_malformed_digests() {
        for mutate in [
            (|d: &mut Measurements| d.nitro.pcr0 = "ab".into()) as fn(&mut Measurements),
            |d: &mut Measurements| d.sp1.range_elf_sha256 = "A".repeat(64),
            |d: &mut Measurements| d.sp1.aggregation_vkey = "1".repeat(64),
            |d: &mut Measurements| d.sp1.range_elf_sha256 = format!("0x{}", "4".repeat(64)),
            |d: &mut Measurements| d.nitro.image_store_path = "/tmp/nope".into(),
        ] {
            let mut d = doc();
            mutate(&mut d);
            assert!(d.validate().is_err());
        }
    }

    /// Enforcement rests on a changed measurement being reported, so every field of the
    /// document must be one `diff` looks at.
    #[test]
    fn diff_covers_every_field() {
        let base = doc();
        let mutations: Vec<(&str, fn(&mut Measurements))> = vec![
            ("sp1.aggregation_vkey", |d| {
                d.sp1.aggregation_vkey = format!("0x{}", "a".repeat(64))
            }),
            ("sp1.range_vkey_commitment", |d| {
                d.sp1.range_vkey_commitment = format!("0x{}", "b".repeat(64))
            }),
            ("sp1.aggregation_elf_sha256", |d| {
                d.sp1.aggregation_elf_sha256 = "c".repeat(64)
            }),
            ("sp1.range_elf_sha256", |d| {
                d.sp1.range_elf_sha256 = "d".repeat(64)
            }),
            ("nitro.pcr0", |d| d.nitro.pcr0 = "e".repeat(96)),
            ("nitro.pcr1", |d| d.nitro.pcr1 = "f".repeat(96)),
            ("nitro.pcr2", |d| d.nitro.pcr2 = "0".repeat(96)),
            ("nitro.tee_image_id", |d| {
                d.nitro.tee_image_id = format!("0x{}", "1".repeat(64))
            }),
            ("nitro.image_store_path", |d| {
                d.nitro.image_store_path = "/nix/store/bbbb-other".into()
            }),
            ("nitro.cli_version", |d| {
                d.nitro.cli_version = "v9.9.9".into()
            }),
        ];

        for (field, mutate) in &mutations {
            let mut changed = base.clone();
            mutate(&mut changed);
            let diff = base.diff(&changed);
            assert_eq!(diff.len(), 1, "{field}: got {diff:#?}");
            assert!(diff[0].contains(field), "{field} not named in {diff:#?}");
        }

        // Catches a field added to the struct but never exercised above.
        assert_eq!(
            base.to_json().as_object().map(|o| o.len()),
            Some(mutations.len()),
            "a measurement field is missing from this test"
        );
        assert!(base.diff(&base).is_empty());
    }
}
