name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  WORLDCHAIN_PROVIDER: "${{ secrets.WORLDCHAIN_PROVIDER }}"
  ETHEREUM_PROVIDER: "${{ secrets.ETHEREUM_PROVIDER }}"

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: pkg/contracts
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@b00af27efadbc7b4ca8b82abbd903b17cc874d2a # v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Build pinned OP Stack artifacts
        run: forge build
        working-directory: pkg/contracts/opstack

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test
