name: Rust CI

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-tests:
    runs-on: arc-public-8xlarge-amd64-runner
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-test-
      - uses: taiki-e/install-action@nextest
      - name: tests
        run: just test

  cargo-lint:
    runs-on: arc-public-8xlarge-amd64-runner
    timeout-minutes: 20
    permissions:
        contents: write
    name: lint
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - uses: foundry-rs/foundry-toolchain@v1

      - uses: taiki-e/install-action@just
      - name: Cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-test-
      - name: Run Formatter
        run: just fmt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "chore: auto-format"
          git push
  
  cargo-clippy:
    runs-on: arc-public-8xlarge-amd64-runner
    timeout-minutes: 20
    name: clippy
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-test-
      - name: clippy
        run: cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings
