name: Rust CI

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            world-chain-builder/target/
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-test-
      - uses: taiki-e/install-action@nextest
      - name: tests
        run: just test

  cargo-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: lint
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            world-chain-builder/target/
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-test-
      - name: fmt + lint
        run: just fmt

