set positional-arguments

devnet-up: build spawn

build:
    docker buildx build -t world-chain-builder:latest -f ../world-chain-builder/Dockerfile ../world-chain-builder

spawn: spawn-op setup-env spawn-builder

spawn-op:
    kurtosis run github.com/ethpandaops/optimism-package --args-file ./kurtosis/network_params.yaml --enclave world-chain

setup-env:
    ./scripts/setup.sh

spawn-builder:
    docker compose up -d --build

devnet-down: 
    kurtosis clean -a
    rm .env


