set positional-arguments

# Tests the world-chain-builder
test: 
  cargo nextest run --workspace

# Formats the world-chain-builder
fmt: fmt-fix fmt-check

fmt-fix:
  cargo +nightly fmt --all

fmt-check:
  cargo +nightly fmt --all -- --check

e2e-test *args='':
    RUST_LOG=debug cargo run -p tests --release -- $@

install *args='':
  cargo install --path crates/world/bin --locked $@